; This file is for the FamiTone2 library and was generated by FamiStudio

music_data_untitled:
	.byte 2
	.word @instruments
	.word @samples-3
; 00 : 1. Intro
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.word 307,256
; 01 : 5. Ghost Town
	.word @song1ch0
	.word @song1ch1
	.word @song1ch2
	.word @song1ch3
	.word @song1ch4
	.word 307,256

@instruments:
	.byte $70 ; 00 : Blip 25to12.5
	.word @env6, @env4, @env9
	.byte $00
	.byte $30 ; 01 : Drums
	.word @env5, @env4, @env4
	.byte $00
	.byte $30 ; 02 : Lead
	.word @env6, @env4, @env9
	.byte $00
	.byte $30 ; 03 : Lead Echo
	.word @env1, @env4, @env4
	.byte $00
	.byte $30 ; 04 : Lead Echo 2
	.word @env8, @env4, @env4
	.byte $00
	.byte $30 ; 05 : Tri Drums
	.word @env7, @env4, @env3
	.byte $00
	.byte $30 ; 06 : Tri Lead
	.word @env0, @env4, @env9
	.byte $00

@env0:
	.byte $cc,$cb,$ca,$c9,$c8,$c8,$c7,$03,$c6,$03,$c5,$0b,$c4,$00,$0c
@env1:
	.byte $ca,$c9,$c9,$c8,$c8,$c7,$c7,$c6,$c6,$c5,$05,$c4,$00,$0b
@env2:
	.byte $cf,$7f,$00,$00
@env3:
	.byte $d8,$00,$00
@env4:
	.byte $c0,$7f,$00,$01
@env5:
	.byte $c6,$c5,$c4,$c3,$c2,$c1,$c0,$00,$06
@env6:
	.byte $ce,$cd,$cd,$cc,$cc,$cb,$cb,$ca,$ca,$c9,$05,$c8,$08,$c8,$00,$0b
@env7:
	.byte $cf,$05,$c0,$00,$02
@env8:
	.byte $c7,$c6,$c6,$c5,$c5,$c4,$c4,$c3,$c3,$c2,$05,$c1,$00,$0b
@env9:
	.byte $c0,$1c,$bf,$c0,$c1,$c2,$c1,$c0,$bf,$be,$00,$02

@samples:
	.byte $00+.lobyte(FT_DPCM_PTR),$0c,$0f	;0 BassDrum (Pitch:15)
	.byte $03+.lobyte(FT_DPCM_PTR),$3f,$06	;1 Gimmick!1.dmc (Pitch:6)
	.byte $03+.lobyte(FT_DPCM_PTR),$3f,$09	;2 Gimmick!1.dmc (Pitch:9)
	.byte $03+.lobyte(FT_DPCM_PTR),$3f,$0b	;3 Gimmick!1.dmc (Pitch:11)
	.byte $03+.lobyte(FT_DPCM_PTR),$3f,$0c	;4 Gimmick!1.dmc (Pitch:12)
	.byte $03+.lobyte(FT_DPCM_PTR),$3f,$0d	;5 Gimmick!1.dmc (Pitch:13)
	.byte $03+.lobyte(FT_DPCM_PTR),$3f,$0f	;6 Gimmick!1.dmc (Pitch:15)
	.byte $13+.lobyte(FT_DPCM_PTR),$3f,$0e	;7 Gimmick!2.dmc (Pitch:14)
	.byte $23+.lobyte(FT_DPCM_PTR),$3f,$09	;8 Gimmick!3.dmc (Pitch:9)
	.byte $23+.lobyte(FT_DPCM_PTR),$3f,$0c	;9 Gimmick!3.dmc (Pitch:12)
	.byte $33+.lobyte(FT_DPCM_PTR),$3f,$0a	;10 Gimmick!4.dmc (Pitch:10)
	.byte $33+.lobyte(FT_DPCM_PTR),$3f,$0d	;11 Gimmick!4.dmc (Pitch:13)
	.byte $33+.lobyte(FT_DPCM_PTR),$3f,$0e	;12 Gimmick!4.dmc (Pitch:14)

@song0ch0:
	.byte $fb, $01
@song0ref3:
	.byte $84, $52, $87, $88, $3a, $87, $84, $48, $87, $88, $52, $87, $84, $42, $87, $88, $48, $87, $84, $3a, $87, $88, $42, $87
	.byte $ff, $10
	.word @song0ref3
	.byte $ff, $10
	.word @song0ref3
	.byte $ff, $10
	.word @song0ref3
@song0ref36:
	.byte $84, $52, $87, $88, $3a, $87, $84, $4a, $87, $88, $52, $87, $84, $40, $87, $88, $4a, $87, $84, $3a, $87, $88, $40, $87
	.byte $ff, $10
	.word @song0ref36
	.byte $ff, $10
	.word @song0ref36
	.byte $ff, $10
	.word @song0ref36
@song0ref69:
	.byte $84, $50, $89, $88, $38, $87, $84, $48, $89, $88, $50, $87, $84, $42, $89, $88, $48, $87, $84, $38, $89, $88, $42, $87
	.byte $ff, $10
	.word @song0ref69
	.byte $ff, $10
	.word @song0ref69
	.byte $ff, $10
	.word @song0ref69
	.byte $84, $4e, $89, $88, $3c, $89, $84, $48, $89, $88, $4e, $89, $84, $42, $89, $88, $48, $89, $84
@song0ref121:
	.byte $3c, $89, $88, $42, $89, $86, $4e, $89, $88, $3c, $89, $86, $48, $89, $88, $4e, $89, $86, $42, $89, $88, $48, $89, $86
	.byte $ff, $10
	.word @song0ref121
	.byte $86, $3c, $89, $88, $42, $89, $4e, $89, $3c, $89, $48, $89, $4e, $89, $42, $89, $48, $89, $3a, $89, $42, $89, $84, $3a
	.byte $f9, $c3
@song0ch0loop:
	.byte $00, $fd
	.word @song0ch0loop
@song0ch1:
	.byte $86, $48, $f9, $f9, $c9, $58, $f9, $f9, $c9, $5a, $f9, $f9, $e9, $54, $f9, $f9, $d9, $00, $f9, $f3
@song0ch1loop:
	.byte $00, $fd
	.word @song0ch1loop
@song0ch2:
	.byte $8c, $52, $f9, $a3, $60, $cd, $5c, $cd, $62, $f9, $f3, $66, $cd, $68, $f9, $b3, $66, $d5, $62, $9b, $66, $99, $62, $9b
	.byte $60, $f9, $f9, $d9, $00, $f9, $f3
@song0ch2loop:
	.byte $00, $fd
	.word @song0ch2loop
@song0ch3:
	.byte $82
@song0ref241:
	.byte $5c, $a5, $5c, $cd, $5a, $91, $58, $91
	.byte $ff, $08
	.word @song0ref241
	.byte $ff, $08
	.word @song0ref241
	.byte $ff, $08
	.word @song0ref241
	.byte $5c, $a9, $5c, $a9, $5c, $a9, $5c, $a9, $5c, $a9, $5c, $a9, $5a, $a9, $58, $a9, $86, $5e, $89, $5c, $89, $5a, $89, $58
	.byte $89, $56, $89, $54, $89, $52, $89, $50, $89, $4e, $89, $4c, $89, $4a, $89, $48, $89, $46, $89, $44, $89, $42, $89, $40
	.byte $89, $5a, $89, $56, $89, $52, $89, $4e, $89, $4a, $89, $46, $89, $42, $89, $40, $89, $5a, $83, $56, $83, $52, $83, $4e
	.byte $83, $4c, $83, $48, $83, $44, $83, $40, $83, $5a, $83, $54, $83, $4e, $83, $48, $83, $40, $83, $48, $83, $50, $83, $5c
	.byte $83, $00, $f9, $c3
@song0ch3loop:
	.byte $00, $fd
	.word @song0ch3loop
@song0ch4:
@song0ref363:
	.byte $03, $12, $a1, $03, $12, $f9, $f9, $9d
	.byte $ff, $08
	.word @song0ref363
	.byte $03, $06, $a5, $03, $06, $f9, $f9, $b9, $03, $04, $a9, $03, $04, $f9, $f9, $f9, $f9, $a1
@song0ch4loop:
	.byte $00, $fd
	.word @song0ch4loop
@song1ch0:
	.byte $fb, $01
@song1ch0loop:
	.byte $f9, $f5, $f9, $f5, $f9, $f5, $f9, $f5, $f9, $f5, $f9, $f5, $f9, $f5, $f9, $f5, $84, $44, $f5, $42, $f5, $3c, $e1, $86
	.byte $42, $87, $3c, $87, $84, $3a, $cd, $42, $a5, $4a, $f5, $4e, $f5, $54, $cd, $58, $a5, $5a, $b9, $60, $b9, $44, $f5, $42
	.byte $f5, $3c, $e1, $86, $42, $87, $3c, $87, $84, $3a, $cd, $42, $a5, $4a, $f5, $4e, $f5, $54, $cd, $58, $a5, $5a, $b9, $60
	.byte $b9, $f9, $b9, $5a, $b9, $5c, $f5, $5a, $cd, $5c, $91, $5a, $91, $44, $b9, $4a, $b9, $5a, $b9, $5c, $b9, $54, $b9, $5c
	.byte $a5, $5a, $87, $5c, $87, $5a, $b9, $60, $b9
@song1ref109:
	.byte $4a, $91, $2c, $87, $88, $22, $87, $84, $32, $87, $88, $2c, $87, $84, $3a, $87, $88, $32, $87, $84, $44, $87, $88, $3a
	.byte $87, $84, $4a, $87, $88, $44, $87, $84, $48, $91, $2a, $87, $88, $22, $87, $84, $30, $87, $88, $2a, $87, $84, $3a, $87
	.byte $88, $30, $87, $84, $42, $87, $88, $3a, $87, $84, $48, $87, $88, $42, $87, $84
	.byte $ff, $2c
	.word @song1ref109
@song1ref176:
	.byte $84, $5c, $91, $4a, $87, $86, $5c, $87, $84, $3a, $87, $86, $4a, $87, $84, $44, $87, $86, $3a, $87, $84, $4a, $87, $86
	.byte $44, $87, $84, $52, $87, $86, $4a, $87, $84, $5a, $91, $2a, $87, $86, $5a, $87, $84, $30, $87, $88, $2a, $87, $84, $42
	.byte $87, $88, $30, $87, $84, $52, $87, $86, $42, $87, $84, $5a, $87, $86, $52, $87
	.byte $ff, $2c
	.word @song1ref176
	.byte $84
	.byte $ff, $2c
	.word @song1ref109
	.byte $84
	.byte $ff, $2c
	.word @song1ref109
	.byte $ff, $2c
	.word @song1ref176
	.byte $ff, $2c
	.word @song1ref176
	.byte $84
	.byte $ff, $2c
	.word @song1ref109
	.byte $84
	.byte $ff, $2c
	.word @song1ref109
	.byte $ff, $2c
	.word @song1ref176
	.byte $ff, $2b
	.word @song1ref176
	.byte $85, $00, $f9, $f5, $f9, $f5, $f9, $f5, $f9, $f5, $fd
	.word @song1ch0loop
@song1ch1:
@song1ch1loop:
	.byte $00, $f9, $f3, $f9, $f5, $f9, $f5, $f9, $f5
@song1ref294:
	.byte $84, $32, $91, $14, $87, $88, $0a, $87, $84, $1a, $87, $88, $14, $87, $84, $22, $87, $88, $1a, $87, $84, $2c, $87, $88
	.byte $22, $87, $84, $32, $87, $88, $2c, $87, $84, $30, $91, $12, $87, $88, $0a, $87, $84, $18, $87, $88, $12, $87, $84, $22
	.byte $87, $88, $18, $87, $84, $2a, $87, $88, $22, $87, $84, $30, $87, $88, $2a, $87
	.byte $ff, $2c
	.word @song1ref294
@song1ref361:
	.byte $84, $44, $91, $32, $87, $86, $44, $87, $84, $22, $87, $86, $32, $87, $84, $2c, $87, $86, $22, $87, $84, $32, $87, $86
	.byte $2c, $87, $84, $3a, $87, $86, $32, $87, $84, $42, $91, $12, $87, $86, $42, $87, $84, $18, $87, $88, $12, $87, $84, $2a
	.byte $87, $88, $18, $87, $84, $3a, $87, $86, $2a, $87, $84, $42, $87, $86, $3a, $87
	.byte $ff, $2c
	.word @song1ref361
	.byte $ff, $2c
	.word @song1ref294
	.byte $ff, $2c
	.word @song1ref294
	.byte $ff, $2c
	.word @song1ref361
	.byte $ff, $2c
	.word @song1ref361
	.byte $ff, $2c
	.word @song1ref294
	.byte $ff, $2c
	.word @song1ref294
	.byte $ff, $2c
	.word @song1ref361
	.byte $ff, $2c
	.word @song1ref361
	.byte $00, $f9, $f3, $f9, $f5, $f9, $f5, $f9, $f5, $f9, $f5, $f9, $f5, $f9, $f5, $f9, $f5, $80, $2c, $91, $44, $91, $3a, $91
	.byte $44, $91, $48, $91, $4a, $91, $48, $b9, $42, $b9, $3c, $91, $24, $91, $3c, $91, $3c, $91, $44, $91, $3c, $91, $3a, $91
	.byte $2a, $91, $30, $91, $3a, $91, $42, $91, $48, $91, $4a, $91, $3a, $91, $44, $91, $4a, $91, $4e, $91, $52, $91, $4e, $b9
	.byte $4a, $b9, $4a, $91, $48, $91, $44, $91, $42, $91, $44, $91, $4a, $91, $48, $b9, $3a, $b9, $14, $91, $2c, $91, $22, $91
	.byte $2c, $91, $30, $91, $32, $91, $30, $b9, $2a, $b9, $24, $91, $0c, $91, $24, $91, $24, $91, $2c, $91, $24, $91, $22, $91
	.byte $12, $91, $18, $91, $22, $91, $2a, $8f, $00, $22, $8f, $00, $32, $91, $22, $91, $2c, $91, $32, $91, $36, $91, $3a, $91
	.byte $36, $b9, $32, $b9, $3c, $a5, $32, $91, $3c, $91, $40, $91, $3c, $91, $3a, $b9, $42, $b9, $84, $44, $a5, $86, $44, $a5
	.byte $88, $44, $a5, $84, $42, $a5, $86, $42, $a5, $88, $42, $a5, $84, $44, $a5, $86, $44, $a5, $88, $44, $a5, $84, $42, $a5
	.byte $86, $42, $a5, $88, $42, $a5, $84, $44, $a5, $86, $44, $a5, $88, $44, $a5, $84, $48, $a5, $86, $48, $a5, $88, $48, $a5
	.byte $84, $4a, $a5, $86, $4a, $a5, $88, $4a, $a5, $84, $42, $a5, $86, $42, $a5, $88, $42, $a5, $fd
	.word @song1ch1loop
@song1ch2:
@song1ch2loop:
@song1ref690:
	.byte $bb, $8a
@song1ref692:
	.byte $52, $91, $00, $e1, $52, $91, $00, $a5, $bb, $52, $91, $00, $e1, $58, $91, $00, $91, $52, $8f, $00, $bb, $52, $91, $00
	.byte $e1, $52, $91, $00, $a5, $bb, $52, $91, $00, $e1, $52, $8f, $00, $4a, $8f, $00, $42, $8f, $00, $bb
	.byte $ff, $2c
	.word @song1ref692
	.byte $ff, $2b
	.word @song1ref692
@song1ref742:
	.byte $8c
@song1ref743:
	.byte $44, $91, $5c, $91, $52, $91, $5c, $91, $60, $91, $62, $91, $60, $b9, $5a, $b9, $54, $91, $3c, $91, $54, $91, $54, $91
	.byte $5c, $91, $54, $91, $52, $91, $42, $91, $48, $91, $52, $91, $5a, $91, $60, $91, $62, $91, $52, $91, $5c, $91, $62, $91
	.byte $66, $91, $6a, $91, $66, $b9, $62, $b9, $8a, $62, $91, $8c, $60, $91, $5c, $91, $5a, $91, $5c, $91, $62, $91, $60, $b9
	.byte $52, $b7, $00
	.byte $ff, $24
	.word @song1ref743
@song1ref821:
	.byte $8a, $5a, $8f, $00, $52, $8f, $00, $8c, $62, $91, $52, $91, $5c, $91, $62, $91, $66, $91, $6a, $91, $66, $b9, $62, $b9
	.byte $6c, $a5, $62, $91, $6c, $91, $70, $91, $6c, $91, $6a, $b9, $72, $b5, $00, $81
	.byte $ff, $2d
	.word @song1ref690
	.byte $ff, $2b
	.word @song1ref692
	.byte $ff, $24
	.word @song1ref742
	.byte $ff, $26
	.word @song1ref821
	.byte $f9, $f5, $f9, $f5, $f9, $f5, $f9, $f5, $fd
	.word @song1ch2loop
@song1ch3:
@song1ch3loop:
	.byte $8c
@song1ref886:
	.byte $5c, $91, $82, $58, $87, $00, $87, $58, $87, $00, $87, $8c, $44, $91, $82, $58, $87, $00, $87, $58, $87, $00, $87, $8c
	.byte $5c, $91, $82, $58, $87, $00, $87, $58, $87, $00, $87, $8c, $44, $91, $82, $58, $87, $00, $87, $58, $87, $00, $87, $8c
	.byte $5c, $91, $82, $58, $87, $00, $87, $58, $87, $00, $87, $8c, $44, $91, $82, $58, $87, $00, $87, $58, $87, $00, $87, $8c
	.byte $5c, $91, $82, $58, $87, $00, $87, $58, $87, $00, $87, $8c, $44, $91, $82, $58, $85, $00, $58, $85, $00, $58, $87, $00
	.byte $87, $8c, $5c, $91, $82, $58, $87, $00, $87, $58, $87, $00, $87, $8c, $44, $91, $82, $58, $87, $00, $87, $58, $87, $00
	.byte $87, $8c, $4a, $91, $82, $58, $87, $00, $87, $58, $87, $00, $87, $8c, $5e, $91, $5c, $91, $5a, $91, $54, $91, $82, $58
	.byte $87, $00, $87, $58, $87, $00, $87, $8c, $52, $91, $82, $58, $87, $00, $87, $58, $87, $00, $87, $8c, $4e, $91, $82, $58
	.byte $87, $00, $87, $58, $87, $00, $87, $8c, $52, $8f, $00, $52, $8f, $00, $44, $8f, $00
	.byte $ff, $9d
	.word @song1ref886
	.byte $ff, $9d
	.word @song1ref886
	.byte $ff, $9d
	.word @song1ref886
	.byte $ff, $9d
	.word @song1ref886
	.byte $ff, $9d
	.word @song1ref886
	.byte $ff, $9d
	.word @song1ref886
	.byte $ff, $9d
	.word @song1ref886
	.byte $ff, $9d
	.word @song1ref886
	.byte $fd
	.word @song1ch3loop
@song1ch4:
@song1ch4loop:
@song1ref1099:
	.byte $02, $83, $08, $8b, $10, $8f, $00, $0c, $8f, $00, $1c, $83, $08, $8b, $0a, $8f, $00, $0c, $8f, $00, $02, $83, $16, $8b
	.byte $1a, $8f, $00, $16, $8f, $00, $1c, $83, $16, $8b, $14, $8f, $00, $16, $8f, $00, $02, $83, $06, $8b, $18, $8f, $00, $06
	.byte $8f, $00, $1c, $83, $18, $8b, $06, $8f, $00, $06, $8f, $00, $02, $83, $16, $8b, $1a, $8f, $00, $0c, $8f, $00, $1c, $83
	.byte $16, $8b, $14, $8f, $00, $0c, $8f, $00
	.byte $ff, $2a
	.word @song1ref1099
@song1ref1182:
	.byte $0a, $8b, $0e, $8f, $00, $0a, $8f, $00, $10, $8f, $00, $0e, $8f, $00, $10, $8f, $00, $02, $83, $1a, $8b, $16, $8f, $00
	.byte $14, $8f, $00, $1a, $8f, $00, $1c, $91, $1c, $91
	.byte $ff, $50
	.word @song1ref1099
	.byte $ff, $2a
	.word @song1ref1099
	.byte $ff, $22
	.word @song1ref1182
	.byte $ff, $50
	.word @song1ref1099
	.byte $ff, $2a
	.word @song1ref1099
	.byte $ff, $22
	.word @song1ref1182
	.byte $ff, $50
	.word @song1ref1099
	.byte $ff, $2a
	.word @song1ref1099
	.byte $ff, $22
	.word @song1ref1182
@song1ref1243:
	.byte $02, $83, $08, $8b, $10, $8f, $00, $08
@song1ref1251:
	.byte $8f, $00, $1c, $83, $08, $8b, $08, $8f, $00, $10, $8f, $00, $02, $83, $16, $8b, $1a, $8f, $00, $16, $8f, $00, $1c, $83
	.byte $16, $8b, $1a, $8f, $00, $16, $8f, $00, $02, $83, $06, $8b, $18, $8f, $00, $06, $8f, $00, $1c, $83, $18, $8b, $06, $8f
	.byte $00, $06, $8f, $00, $02, $83, $16, $8b, $1a, $8f, $00, $1a, $8f, $00, $1c, $83, $16, $8b, $1a, $8f, $00, $16, $8f, $00
	.byte $02, $83, $08, $8b, $10, $8f, $00, $10
	.byte $ff, $22
	.word @song1ref1251
@song1ref1334:
	.byte $0a, $8b, $0e, $8f, $00, $0a, $8f, $00, $0a, $8f, $00, $0e, $8f, $00, $0a, $8f, $00, $02, $83, $1a, $8b, $16, $8f, $00
	.byte $1a, $8f, $00, $1a, $8f, $00, $02, $83, $1a, $89, $00, $1a, $8f, $00
	.byte $ff, $50
	.word @song1ref1099
	.byte $ff, $2a
	.word @song1ref1099
	.byte $ff, $22
	.word @song1ref1182
	.byte $ff, $50
	.word @song1ref1099
	.byte $ff, $2a
	.word @song1ref1099
	.byte $ff, $22
	.word @song1ref1182
	.byte $ff, $50
	.word @song1ref1099
	.byte $ff, $2a
	.word @song1ref1099
	.byte $ff, $22
	.word @song1ref1182
	.byte $ff, $58
	.word @song1ref1243
	.byte $ff, $22
	.word @song1ref1251
	.byte $ff, $26
	.word @song1ref1334
	.byte $fd
	.word @song1ch4loop
