; This file is for the FamiTone2 library and was generated by FamiStudio

music_data_gimmick:
	.byte 5
	.word @instruments
	.word @samples-3
; 00 : 5. Ghost Town
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.word 307,256
; 01 : Farewell
	.word @song1ch0
	.word @song1ch1
	.word @song1ch2
	.word @song1ch3
	.word @song1ch4
	.word 307,256
; 02 : 5. Ghost TownDedrecil
	.word @song2ch0
	.word @song2ch1
	.word @song2ch2
	.word @song2ch3
	.word @song2ch4
	.word 307,256
; 03 : Stickerbrush Symphony
	.word @song3ch0
	.word @song3ch1
	.word @song3ch2
	.word @song3ch3
	.word @song3ch4
	.word 307,256
; 04 : IrisLaylaTheIris
	.word @song4ch0
	.word @song4ch1
	.word @song4ch2
	.word @song4ch3
	.word @song4ch4
	.word 307,256

@instruments:
	.byte $70 ; 00 : Background
	.word @env5, @env15, @env15
	.byte $00
	.byte $30 ; 01 : Bass
	.word @env5, @env15, @env15
	.byte $00
	.byte $70 ; 02 : BeepEcho
	.word @env4, @env15, @env24
	.byte $00
	.byte $70 ; 03 : Blip 25to12.5
	.word @env20, @env15, @env28
	.byte $00
	.byte $30 ; 04 : Closed Hat
	.word @env29, @env10, @env15
	.byte $00
	.byte $30 ; 05 : Drums
	.word @env17, @env15, @env15
	.byte $00
	.byte $30 ; 06 : HiHat
	.word @env6, @env19, @env15
	.byte $00
	.byte $30 ; 07 : Lead
	.word @env20, @env15, @env28
	.byte $00
	.byte $30 ; 08 : Lead Echo
	.word @env2, @env15, @env15
	.byte $00
	.byte $30 ; 09 : Lead Echo 2
	.word @env26, @env15, @env15
	.byte $00
	.byte $30 ; 0a : LeadDuty0 LaylaTheIris
	.word @env9, @env15, @env15
	.byte $00
	.byte $70 ; 0b : LeadDuty1 LaylaTheIris
	.word @env9, @env15, @env15
	.byte $00
	.byte $70 ; 0c : LeadDuty1Drop LaylaTheIris
	.word @env5, @env8, @env15
	.byte $00
	.byte $b0 ; 0d : LeadDuty2 LaylaTheIris
	.word @env9, @env15, @env15
	.byte $00
	.byte $b0 ; 0e : LeadDuty2Drop LaylaTheIris
	.word @env5, @env8, @env15
	.byte $00
	.byte $30 ; 0f : LeadLow
	.word @env23, @env15, @env27
	.byte $00
	.byte $70 ; 10 : Noise Kick
	.word @env3, @env18, @env15
	.byte $00
	.byte $70 ; 11 : Noise Snare
	.word @env1, @env12, @env15
	.byte $00
	.byte $70 ; 12 : NoiseBassDrum LaylaTheIris
	.word @env16, @env15, @env15
	.byte $00
	.byte $30 ; 13 : NoiseCrash LaylaTheIris
	.word @env13, @env15, @env15
	.byte $00
	.byte $30 ; 14 : NoiseHiHat LaylaTheIris
	.word @env16, @env15, @env15
	.byte $00
	.byte $30 ; 15 : NoiseSnare LaylaTheIris
	.word @env11, @env15, @env15
	.byte $00
	.byte $30 ; 16 : Open Hat
	.word @env21, @env22, @env15
	.byte $00
	.byte $30 ; 17 : Tri Drums
	.word @env25, @env15, @env14
	.byte $00
	.byte $30 ; 18 : Tri Lead
	.word @env0, @env15, @env28
	.byte $00
	.byte $30 ; 19 : TriBass LaylaTheIris
	.word @env5, @env15, @env15
	.byte $00
	.byte $30 ; 1a : TriBassDrum LaylaTheIris
	.word @env5, @env7, @env15
	.byte $00

@env0:
	.byte $cc,$cb,$ca,$c9,$c8,$c8,$c7,$03,$c6,$03,$c5,$0b,$c4,$00,$0c
@env1:
	.byte $c6,$c1,$c2,$c6,$c5,$c4,$c3,$c2,$c1,$c1,$c0,$00,$0a
@env2:
	.byte $ca,$c9,$c9,$c8,$c8,$c7,$c7,$c6,$c6,$c5,$05,$c4,$00,$0b
@env3:
	.byte $c7,$c2,$c0,$00,$02
@env4:
	.byte $c8,$c7,$c6,$c5,$00,$03
@env5:
	.byte $cf,$7f,$00,$00
@env6:
	.byte $ca,$ca,$c7,$c6,$c6,$c5,$04,$c4,$c3,$c2,$c1,$05,$c0,$00,$0c
@env7:
	.byte $c0,$bd,$ba,$b7,$b4,$b1,$00,$05
@env8:
	.byte $c0,$bc,$b8,$b4,$b0,$ac,$a8,$00,$06
@env9:
	.byte $ca,$7f,$00,$00
@env10:
	.byte $ca,$cb,$cb,$cc,$cc,$cd,$cd,$ce,$00,$07
@env11:
	.byte $c7,$04,$c0,$00,$02
@env12:
	.byte $c4,$c9,$c9,$c8,$c8,$c9,$00,$05
@env13:
	.byte $ce,$02,$cd,$02,$cc,$02,$cb,$03,$ca,$02,$c9,$02,$c8,$02,$c7,$03,$c6,$02,$c5,$02,$c4,$02,$c3,$00,$16
@env14:
	.byte $d8,$00,$00
@env15:
	.byte $c0,$7f,$00,$01
@env16:
	.byte $cd,$cb,$c9,$c7,$c5,$c0,$00,$05
@env17:
	.byte $c6,$c5,$c4,$c3,$c2,$c1,$c0,$00,$06
@env18:
	.byte $c6,$c9,$00,$01
@env19:
	.byte $c0,$c1,$03,$c2,$c1,$c2,$c1,$c2,$c1,$c2,$00,$09
@env20:
	.byte $ce,$cd,$cd,$cc,$cc,$cb,$cb,$ca,$ca,$c9,$05,$c8,$08,$c8,$00,$0b
@env21:
	.byte $c8,$c6,$c5,$c5,$c4,$c3,$02,$c2,$02,$c1,$0c,$c0,$00,$0b
@env22:
	.byte $c9,$ca,$ca,$cb,$cb,$cc,$03,$cd,$cc,$00,$07
@env23:
	.byte $c4,$c3,$c2,$00,$02
@env24:
	.byte $c1,$04,$c0,$00,$02
@env25:
	.byte $cf,$05,$c0,$00,$02
@env26:
	.byte $c7,$c6,$c6,$c5,$c5,$c4,$c4,$c3,$c3,$c2,$05,$c1,$00,$0b
@env27:
	.byte $c0,$11,$c0,$c1,$c2,$c2,$c1,$c0,$bf,$be,$bd,$be,$bf,$00,$02
@env28:
	.byte $c0,$1c,$bf,$c0,$c1,$c2,$c1,$c0,$bf,$be,$00,$02
@env29:
	.byte $c7,$c6,$c5,$c4,$c3,$c2,$c1,$04,$c0,$00,$08

@samples:
	.byte $14+.lobyte(FT_DPCM_PTR),$0c,$0f	;0 BassDrumDedrecil (Pitch:15)
	.byte $17+.lobyte(FT_DPCM_PTR),$3f,$0b	;4 Gimmick!1.dmcDedrecil (Pitch:11)
	.byte $17+.lobyte(FT_DPCM_PTR),$3f,$0c	;5 Gimmick!1.dmcDedrecil (Pitch:12)
	.byte $17+.lobyte(FT_DPCM_PTR),$3f,$0d	;6 Gimmick!1.dmcDedrecil (Pitch:13)
	.byte $17+.lobyte(FT_DPCM_PTR),$3f,$0f	;7 Gimmick!1.dmcDedrecil (Pitch:15)
	.byte $27+.lobyte(FT_DPCM_PTR),$3f,$0e	;8 Gimmick!2.dmcDedrecil (Pitch:14)
	.byte $37+.lobyte(FT_DPCM_PTR),$3f,$0c	;9 Gimmick!3.dmcDedrecil (Pitch:12)
	.byte $00+.lobyte(FT_DPCM_PTR),$50,$0f	;13 GimmickBass0F (Pitch:15)

@song0ch0:
	.byte $fb, $01
@song0ch0loop:
	.byte $f9, $f5, $f9, $f5, $f9, $f5, $f9, $f5, $f9, $f5, $f9, $f5, $f9, $f5, $f9, $f5, $8e, $44, $f5, $42, $f5, $3c, $e1, $90
	.byte $42, $87, $3c, $87, $8e, $3a, $cd, $42, $a5, $4a, $f5, $4e, $f5, $54, $cd, $58, $a5, $5a, $b9, $60, $b9, $44, $f5, $42
	.byte $f5, $3c, $e1, $90, $42, $87, $3c, $87, $8e, $3a, $cd, $42, $a5, $4a, $f5, $4e, $f5, $54, $cd, $58, $a5, $5a, $b9, $60
	.byte $b9, $f9, $b9, $5a, $b9, $5c, $f5, $5a, $cd, $5c, $91, $5a, $91, $44, $b9, $4a, $b9, $5a, $b9, $5c, $b9, $54, $b9, $5c
	.byte $a5, $5a, $87, $5c, $87, $5a, $b9, $60, $b9
@song0ref109:
	.byte $4a, $91, $2c, $87, $92, $22, $87, $8e, $32, $87, $92, $2c, $87, $8e, $3a, $87, $92, $32, $87, $8e, $44, $87, $92, $3a
	.byte $87, $8e, $4a, $87, $92, $44, $87, $8e, $48, $91, $2a, $87, $92, $22, $87, $8e, $30, $87, $92, $2a, $87, $8e, $3a, $87
	.byte $92, $30, $87, $8e, $42, $87, $92, $3a, $87, $8e, $48, $87, $92, $42, $87, $8e
	.byte $ff, $2c
	.word @song0ref109
@song0ref176:
	.byte $8e, $5c, $91, $4a, $87, $90, $5c, $87, $8e, $3a, $87, $90, $4a, $87, $8e, $44, $87, $90, $3a, $87, $8e, $4a, $87, $90
	.byte $44, $87, $8e, $52, $87, $90, $4a, $87, $8e, $5a, $91, $2a, $87, $90, $5a, $87, $8e, $30, $87, $92, $2a, $87, $8e, $42
	.byte $87, $92, $30, $87, $8e, $52, $87, $90, $42, $87, $8e, $5a, $87, $90, $52, $87
	.byte $ff, $2c
	.word @song0ref176
	.byte $8e
	.byte $ff, $2c
	.word @song0ref109
	.byte $8e
	.byte $ff, $2c
	.word @song0ref109
	.byte $ff, $2c
	.word @song0ref176
	.byte $ff, $2c
	.word @song0ref176
	.byte $8e
	.byte $ff, $2c
	.word @song0ref109
	.byte $8e
	.byte $ff, $2c
	.word @song0ref109
	.byte $ff, $2c
	.word @song0ref176
	.byte $ff, $2b
	.word @song0ref176
	.byte $85, $00, $f9, $f5, $f9, $f5, $f9, $f5, $f9, $f5, $fd
	.word @song0ch0loop
@song0ch1:
@song0ch1loop:
	.byte $00, $f9, $f3, $f9, $f5, $f9, $f5, $f9, $f5
@song0ref294:
	.byte $8e, $32, $91, $14, $87, $92, $0a, $87, $8e, $1a, $87, $92, $14, $87, $8e, $22, $87, $92, $1a, $87, $8e, $2c, $87, $92
	.byte $22, $87, $8e, $32, $87, $92, $2c, $87, $8e, $30, $91, $12, $87, $92, $0a, $87, $8e, $18, $87, $92, $12, $87, $8e, $22
	.byte $87, $92, $18, $87, $8e, $2a, $87, $92, $22, $87, $8e, $30, $87, $92, $2a, $87
	.byte $ff, $2c
	.word @song0ref294
@song0ref361:
	.byte $8e, $44, $91, $32, $87, $90, $44, $87, $8e, $22, $87, $90, $32, $87, $8e, $2c, $87, $90, $22, $87, $8e, $32, $87, $90
	.byte $2c, $87, $8e, $3a, $87, $90, $32, $87, $8e, $42, $91, $12, $87, $90, $42, $87, $8e, $18, $87, $92, $12, $87, $8e, $2a
	.byte $87, $92, $18, $87, $8e, $3a, $87, $90, $2a, $87, $8e, $42, $87, $90, $3a, $87
	.byte $ff, $2c
	.word @song0ref361
	.byte $ff, $2c
	.word @song0ref294
	.byte $ff, $2c
	.word @song0ref294
	.byte $ff, $2c
	.word @song0ref361
	.byte $ff, $2c
	.word @song0ref361
	.byte $ff, $2c
	.word @song0ref294
	.byte $ff, $2c
	.word @song0ref294
	.byte $ff, $2c
	.word @song0ref361
	.byte $ff, $2c
	.word @song0ref361
	.byte $00, $f9, $f3, $f9, $f5, $f9, $f5, $f9, $f5, $f9, $f5, $f9, $f5, $f9, $f5, $f9, $f5, $86, $2c, $91, $44, $91, $3a, $91
	.byte $44, $91, $48, $91, $4a, $91, $48, $b9, $42, $b9, $3c, $91, $24, $91, $3c, $91, $3c, $91, $44, $91, $3c, $91, $3a, $91
	.byte $2a, $91, $30, $91, $3a, $91, $42, $91, $48, $91, $4a, $91, $3a, $91, $44, $91, $4a, $91, $4e, $91, $52, $91, $4e, $b9
	.byte $4a, $b9, $4a, $91, $48, $91, $44, $91, $42, $91, $44, $91, $4a, $91, $48, $b9, $3a, $b9, $14, $91, $2c, $91, $22, $91
	.byte $2c, $91, $30, $91, $32, $91, $30, $b9, $2a, $b9, $24, $91, $0c, $91, $24, $91, $24, $91, $2c, $91, $24, $91, $22, $91
	.byte $12, $91, $18, $91, $22, $91, $2a, $8f, $00, $22, $8f, $00, $32, $91, $22, $91, $2c, $91, $32, $91, $36, $91, $3a, $91
	.byte $36, $b9, $32, $b9, $3c, $a5, $32, $91, $3c, $91, $40, $91, $3c, $91, $3a, $b9, $42, $b9, $8e, $44, $a5, $90, $44, $a5
	.byte $92, $44, $a5, $8e, $42, $a5, $90, $42, $a5, $92, $42, $a5, $8e, $44, $a5, $90, $44, $a5, $92, $44, $a5, $8e, $42, $a5
	.byte $90, $42, $a5, $92, $42, $a5, $8e, $44, $a5, $90, $44, $a5, $92, $44, $a5, $8e, $48, $a5, $90, $48, $a5, $92, $48, $a5
	.byte $8e, $4a, $a5, $90, $4a, $a5, $92, $4a, $a5, $8e, $42, $a5, $90, $42, $a5, $92, $42, $a5, $fd
	.word @song0ch1loop
@song0ch2:
@song0ch2loop:
@song0ref690:
	.byte $bb, $ae
@song0ref692:
	.byte $52, $91, $00, $e1, $52, $91, $00, $a5, $bb, $52, $91, $00, $e1, $58, $91, $00, $91, $52, $8f, $00, $bb, $52, $91, $00
	.byte $e1, $52, $91, $00, $a5, $bb, $52, $91, $00, $e1, $52, $8f, $00, $4a, $8f, $00, $42, $8f, $00, $bb
	.byte $ff, $2c
	.word @song0ref692
	.byte $ff, $2b
	.word @song0ref692
@song0ref742:
	.byte $b0
@song0ref743:
	.byte $44, $91, $5c, $91, $52, $91, $5c, $91, $60, $91, $62, $91, $60, $b9, $5a, $b9, $54, $91, $3c, $91, $54, $91, $54, $91
	.byte $5c, $91, $54, $91, $52, $91, $42, $91, $48, $91, $52, $91, $5a, $91, $60, $91, $62, $91, $52, $91, $5c, $91, $62, $91
	.byte $66, $91, $6a, $91, $66, $b9, $62, $b9, $ae, $62, $91, $b0, $60, $91, $5c, $91, $5a, $91, $5c, $91, $62, $91, $60, $b9
	.byte $52, $b7, $00
	.byte $ff, $24
	.word @song0ref743
@song0ref821:
	.byte $ae, $5a, $8f, $00, $52, $8f, $00, $b0, $62, $91, $52, $91, $5c, $91, $62, $91, $66, $91, $6a, $91, $66, $b9, $62, $b9
	.byte $6c, $a5, $62, $91, $6c, $91, $70, $91, $6c, $91, $6a, $b9, $72, $b5, $00, $81
	.byte $ff, $2d
	.word @song0ref690
	.byte $ff, $2b
	.word @song0ref692
	.byte $ff, $24
	.word @song0ref742
	.byte $ff, $26
	.word @song0ref821
	.byte $f9, $f5, $f9, $f5, $f9, $f5, $f9, $f5, $fd
	.word @song0ch2loop
@song0ch3:
@song0ch3loop:
	.byte $b0
@song0ref886:
	.byte $5c, $91, $8a, $58, $87, $00, $87, $58, $87, $00, $87, $b0, $44, $91, $8a, $58, $87, $00, $87, $58, $87, $00, $87, $b0
	.byte $5c, $91, $8a, $58, $87, $00, $87, $58, $87, $00, $87, $b0, $44, $91, $8a, $58, $87, $00, $87, $58, $87, $00, $87, $b0
	.byte $5c, $91, $8a, $58, $87, $00, $87, $58, $87, $00, $87, $b0, $44, $91, $8a, $58, $87, $00, $87, $58, $87, $00, $87, $b0
	.byte $5c, $91, $8a, $58, $87, $00, $87, $58, $87, $00, $87, $b0, $44, $91, $8a, $58, $85, $00, $58, $85, $00, $58, $87, $00
	.byte $87, $b0, $5c, $91, $8a, $58, $87, $00, $87, $58, $87, $00, $87, $b0, $44, $91, $8a, $58, $87, $00, $87, $58, $87, $00
	.byte $87, $b0, $4a, $91, $8a, $58, $87, $00, $87, $58, $87, $00, $87, $b0, $5e, $91, $5c, $91, $5a, $91, $54, $91, $8a, $58
	.byte $87, $00, $87, $58, $87, $00, $87, $b0, $52, $91, $8a, $58, $87, $00, $87, $58, $87, $00, $87, $b0, $4e, $91, $8a, $58
	.byte $87, $00, $87, $58, $87, $00, $87, $b0, $52, $8f, $00, $52, $8f, $00, $44, $8f, $00
	.byte $ff, $9d
	.word @song0ref886
	.byte $ff, $9d
	.word @song0ref886
	.byte $ff, $9d
	.word @song0ref886
	.byte $ff, $9d
	.word @song0ref886
	.byte $ff, $9d
	.word @song0ref886
	.byte $ff, $9d
	.word @song0ref886
	.byte $ff, $9d
	.word @song0ref886
	.byte $ff, $9d
	.word @song0ref886
	.byte $fd
	.word @song0ch3loop
@song0ch4:
@song0ch4loop:
@song0ref1099:
	.byte $a5, $00, $91, $00, $a5, $00, $91, $00, $a5, $00, $91, $00, $a5, $00, $91, $00, $85, $1c, $9d, $00, $1c, $8f, $00, $93
	.byte $1c, $8f, $00, $1c, $8f, $00, $a5, $00, $91, $00, $a5, $00, $91, $00, $a5, $00, $91, $00, $a5, $00, $91, $00, $a5, $00
	.byte $91, $00, $a5, $00, $91, $00, $a5, $00, $91, $00, $91, $00, $91, $00, $91, $00, $a5, $00, $91, $00, $91, $00, $a7
	.byte $ff, $47
	.word @song0ref1099
	.byte $ff, $47
	.word @song0ref1099
	.byte $ff, $47
	.word @song0ref1099
	.byte $ff, $46
	.word @song0ref1099
	.byte $91, $00, $91, $00
	.byte $ff, $47
	.word @song0ref1099
	.byte $ff, $47
	.word @song0ref1099
	.byte $ff, $47
	.word @song0ref1099
	.byte $ff, $46
	.word @song0ref1099
	.byte $91, $00, $91, $00, $fd
	.word @song0ch4loop
@song1ch0:
	.byte $fb, $01
@song1ch0loop:
@song1ref4:
	.byte $84, $36, $8b, $3a, $87, $37, $3c
@song1ref11:
	.byte $87, $37
@song1ref13:
	.byte $44, $87, $3b, $4e, $87, $3d, $52, $87, $45, $54, $87, $4f, $5c, $87, $53, $36, $87, $55, $3a, $87, $5d, $3c, $87, $37
	.byte $44, $87, $3b, $4e, $87, $3d, $52, $87, $45, $54, $87, $4f, $5c, $87, $53, $32, $87, $55, $36, $87, $5d, $3a, $87, $33
	.byte $40, $87, $37, $4a, $87, $3b, $4e, $87, $41, $52, $87, $4b, $58, $87, $4f, $32, $87, $53, $36, $87, $59, $3a, $87, $33
	.byte $40, $87, $37, $4a, $87, $3b, $4e, $87, $41, $52, $87, $4b, $58, $87, $4e, $81, $30, $87, $53, $32, $87, $59, $36, $87
	.byte $31, $3c, $87, $33, $48, $87, $37, $4a, $87, $3d, $4e, $87, $49, $54, $87, $4b, $30, $87, $4f, $32, $87, $55, $36, $87
	.byte $31, $3c, $87, $33, $48, $87, $37, $4a, $87, $3d, $4e, $87, $49, $54, $87, $4b, $2e, $87, $4f, $32, $87, $55
@song1ref155:
	.byte $36, $87, $2f, $3c, $87, $33, $46, $87, $37, $4a, $87, $3d, $4e, $87, $47, $54, $87, $4b, $2e, $87, $4f, $32, $87, $55
	.byte $36, $87, $2f, $3c, $87, $33, $46, $87, $37, $4a, $87, $3d, $4e, $87, $47, $54, $87, $4a, $81, $2c, $87, $4f, $30, $87
	.byte $55, $32, $87, $2d, $3a, $87, $31, $44, $87, $33, $48, $87, $3b, $4a, $87, $45, $52, $87, $49, $2c, $87, $4b, $30, $87
	.byte $53, $32, $87, $2d, $3a, $87, $31, $44, $87, $33, $48, $87, $3b, $4a, $87, $45, $52, $87, $49, $2e, $87, $4b, $32, $87
	.byte $53
	.byte $ff, $2b
	.word @song1ref155
@song1ref255:
	.byte $30, $87, $4f, $32, $87, $55, $36, $87, $31, $40, $87, $33, $48, $87, $37, $4a, $87, $41, $4e, $87, $49, $58, $87, $4b
	.byte $30, $87, $4f, $32, $87, $59, $36, $87, $31, $40, $87, $33, $48, $87, $37, $4a, $87, $41, $4e, $87, $49, $58, $87, $4b
	.byte $32, $87, $4f, $4a, $87, $59, $4e, $87, $33, $52, $87, $4b, $36, $87, $4f, $4a, $87, $53, $4e, $87, $37, $52, $87, $4b
	.byte $3a, $87, $4f, $4a, $87, $53, $4e, $87, $3b, $52, $87, $4b, $44, $87, $4f, $4a, $87, $53, $4e, $87, $45, $52, $87, $4a
	.byte $81, $36, $8b, $3a, $87, $37, $3c, $8b
	.byte $ff, $d1
	.word @song1ref13
	.byte $24, $87, $4b, $28, $87, $53, $2c, $87, $25, $32, $87, $29, $3c, $87, $2d, $40, $87, $33, $44, $87, $3d, $4a, $87, $41
	.byte $24, $87, $45, $28, $87, $4b, $2a, $87, $25, $32, $87, $29, $3c, $87, $2b, $40, $87, $33, $42, $87, $3d, $4a, $87, $41
	.byte $24, $87, $43, $28, $87, $4b, $2a, $87, $25, $32, $87, $29, $28, $87, $2b, $2a, $87, $33, $32, $87, $29, $40, $87, $2a
	.byte $81, $28, $87, $33, $2c, $87, $41, $2e, $87, $29, $36, $87, $2d, $2c, $87, $2f, $2e, $87, $37, $36, $87, $2d, $3c, $87
	.byte $2f, $2e, $87, $37, $36, $87, $3d, $3c, $87, $2f, $44, $87, $37, $36, $87, $3d, $3c, $87, $45, $44, $87, $37, $4e, $87
	.byte $3d, $24, $87, $45, $28, $87, $4f, $32, $87, $25, $3c, $87, $29, $40, $87, $33, $4a, $87, $3d, $54, $87, $41, $58, $87
	.byte $4b, $62, $87, $55, $58, $8b, $54, $87, $63, $52, $87, $59, $4a, $87, $55, $40, $87, $53, $3c, $87, $4b, $3a, $87, $40
	.byte $81, $8e
@song1ref532:
	.byte $3c, $ed, $9e, $4e, $b5, $5c, $a7, $66, $a7, $66, $ed, $62, $a7, $5c, $a7, $58, $97, $5c, $5c, $f9, $d5, $58, $8b, $56
	.byte $f9, $8f, $56, $8b, $58, $8b, $5c, $8b, $58, $8b, $8e, $3c, $ed, $9e, $4e, $b5, $5c, $a7, $66, $a7, $66, $ed, $62, $a7
	.byte $5c, $a7, $58, $97, $5c, $5c, $d1, $8e, $56, $9f, $5d, $5c, $a3, $66, $9d, $57, $66, $f9, $ab, $46, $8b, $48, $8b, $4a
	.byte $8b, $4c, $8b
	.byte $ff, $3b
	.word @song1ref532
	.byte $56, $56, $66, $f9, $e3
	.byte $ff, $f7
	.word @song1ref4
	.byte $ff, $2b
	.word @song1ref155
	.byte $ff, $67
	.word @song1ref255
	.byte $ff, $f1
	.word @song1ref11
	.byte $ff, $2b
	.word @song1ref155
	.byte $ff, $61
	.word @song1ref255
	.byte $8e, $54, $ed, $54, $a3, $62, $9f, $55, $62, $9d, $55, $58, $f9, $e1, $00, $fd
	.word @song1ch0loop
@song1ch1:
@song1ch1loop:
	.byte $8e
@song1ref653:
	.byte $44, $f9, $99, $4e, $a3, $5c, $f9, $97, $52, $a3, $58, $a3, $62, $a1, $66, $f9, $99, $6a, $a3, $6c, $f9, $97, $54, $a3
	.byte $58, $a3, $5c, $a1, $62, $f9, $99, $66, $a3, $6a, $a1, $6a, $ed, $66, $b5, $5c, $b5, $6a, $ed, $66, $a3, $5c, $a3, $62
	.byte $f9, $f9, $8d
	.byte $ff, $1d
	.word @song1ref653
	.byte $ed, $54, $a3, $58, $a3, $5c, $a1, $62, $b5, $5e, $b5, $54, $b5, $58, $b5, $5e, $b5, $5c, $b5, $54, $b5, $4e, $b5, $54
	.byte $ed, $52, $ed
@song1ref734:
	.byte $4e, $f9, $8f, $5c, $a7, $66, $a7, $66, $ed, $62, $a7, $5c, $a7, $58, $99, $5c, $f9, $d5, $58, $8b, $56, $f9, $8f, $56
	.byte $8b, $58, $8b, $5c, $8b, $58, $8b, $54, $8b, $52, $8b, $4e, $f9, $8f, $5c, $a7, $66, $a7, $66, $ed, $62, $a7, $5c, $a7
	.byte $58, $99, $5c, $ed, $5c, $a3, $66, $a3, $70, $a1, $6e, $f9, $e3
	.byte $ff, $3d
	.word @song1ref734
	.byte $ff, $33
	.word @song1ref653
	.byte $ff, $33
	.word @song1ref653
	.byte $62, $ed, $6c, $a3, $70, $a3, $7a, $a1, $02, $f9, $e1, $00, $fd
	.word @song1ch1loop
@song1ch2:
@song1ch2loop:
	.byte $82
@song1ref821:
	.byte $32, $8b, $36, $f9, $d5, $32, $f9, $e3, $30, $f9, $e3, $2e, $f9, $e3, $2c, $a7, $00, $8b, $2c, $a7, $00, $8b, $2c, $a7
	.byte $00, $8b, $2c, $a7, $00, $8b
@song1ref851:
	.byte $2e, $a7, $00, $8b, $2e, $a7, $00, $8b, $2e, $a7, $00, $8b, $2e, $a7, $00, $8b, $30, $a7, $00, $8b, $30, $a7, $00, $8b
	.byte $30, $a7, $00, $8b, $30, $a7, $00, $8b, $32, $a7, $00, $8b, $36, $a7, $00, $8b, $3a, $9d, $3a, $95, $44, $b5, $36, $c1
	.byte $36, $a9, $4e, $d1, $4a, $8b, $4e, $8b, $4a, $ed, $3a, $a3, $40, $a3, $4a, $a1, $48, $ed, $30, $ed, $46, $ed, $3c, $a3
	.byte $40, $a3, $44, $a1, $2c, $a7, $00, $8b, $2c, $a7, $00, $8b, $2c, $a7, $00, $8b, $2c, $a7, $00, $8b, $2a, $a7, $00, $8b
	.byte $2a, $a7, $00, $8b, $2a, $a7, $00, $8b, $2a, $a7, $00, $8b, $28, $a7, $00, $8b, $2c, $a7, $00, $8b, $2e, $a7, $00, $8b
	.byte $2e, $a7, $00, $8b, $32, $a7, $00, $8b, $32, $a7, $00, $8b, $32, $a7, $00, $8b, $32, $a7, $00, $8b, $2e, $91, $00, $85
	.byte $46, $91, $00, $85, $46, $87, $01, $2e, $91, $00, $85, $2e, $87, $01, $2e, $a7, $00, $8b, $2e, $91, $00, $85
@song1ref1017:
	.byte $2e, $87, $01, $30, $87, $01, $32, $91, $00, $85
@song1ref1027:
	.byte $4a, $91, $00, $85, $4a, $87, $01, $32, $91, $00, $85, $32, $87, $01, $32, $a7, $00, $8b, $32, $91, $00, $85, $32, $87
	.byte $01, $32, $87, $00, $81, $36, $a7, $00, $8b, $36, $a7, $00, $8b, $36, $a7, $00, $8b, $36, $9d, $00, $87, $2c, $87, $01
	.byte $36, $91, $00, $85, $4e, $91, $00, $85, $4e, $87, $01, $36, $91, $00, $85, $36, $87, $01, $36, $91, $00, $85
@song1ref1097:
	.byte $36, $87, $01, $3a, $87, $01, $3c, $87, $01, $3a, $87, $01, $36, $87, $01, $32, $87, $00, $81, $2e, $91, $00, $85, $46
	.byte $91, $00, $85, $46, $87, $01, $2e, $91, $00, $85, $2e, $87, $01, $2e, $a7, $00, $8b, $2e, $93, $00, $83
	.byte $ff, $37
	.word @song1ref1017
@song1ref1145:
	.byte $44, $87, $01, $36, $91, $00, $85, $4e, $91, $00, $85, $4e, $87, $01, $36, $91, $00, $85, $36, $87, $01, $36, $a7, $00
	.byte $8b, $36, $89, $36, $a9, $2e, $93, $00, $83, $46, $91, $00, $85, $46, $87, $01, $2e, $91, $00, $85, $2e, $87, $01, $2e
	.byte $a7, $00, $8b, $2e, $93, $00, $83
	.byte $ff, $46
	.word @song1ref1017
	.byte $93, $00, $83, $36, $87, $01, $36, $93, $00, $83
	.byte $ff, $2d
	.word @song1ref1097
	.byte $2e, $87, $01, $30, $87, $01, $32, $93, $00, $83
	.byte $ff, $2d
	.word @song1ref1027
	.byte $ff, $1d
	.word @song1ref1145
	.byte $ff, $7a
	.word @song1ref821
	.byte $ff, $21
	.word @song1ref851
	.byte $ad, $00, $85, $36, $ab, $00, $87, $3a, $ab, $00, $87, $32, $ab, $00, $87, $34, $f9, $e3, $32, $f9, $e1, $00, $fd
	.word @song1ch2loop
@song1ch3:
@song1ch3loop:
	.byte $b7, $8c
@song1ref1266:
	.byte $5a, $99, $5a, $8b, $5a, $8b, $5a, $b5, $5a, $ed, $5a, $99, $5a, $8b, $5a, $8b, $5a, $b5, $5a, $b5, $b7, $5a, $99, $5a
	.byte $8b, $5a, $8b, $5a, $b5, $5a, $ed, $5a, $99, $5a, $8b, $5a, $8b, $5a, $d1, $5a, $99, $a9, $5a, $b5, $5a, $b5, $5a, $b5
	.byte $5a, $b5, $5a, $b5, $5a, $b5, $5a, $c3, $a9, $5a, $b5, $5a, $b5, $5a, $ed, $5a, $b5, $5a, $b5, $5a, $c3, $b7
	.byte $ff, $45
	.word @song1ref1266
@song1ref1339:
	.byte $5a, $8b, $5a, $99, $5a, $99, $5a, $8b, $5a, $8b, $5a, $8b, $5a, $8b, $5a, $8b, $5a, $8b, $5a, $99, $5a, $8b, $5a, $8b
	.byte $5a, $8b, $5a, $8b, $5a, $8b, $5a, $8b, $5a, $99, $5a, $8b, $5a, $8b, $5a, $8b, $5a, $8b, $5a, $8b, $5a, $8b, $5a, $99
	.byte $5a, $8b, $5a, $8b, $5a, $8b
	.byte $ff, $2f
	.word @song1ref1339
	.byte $c3
	.byte $ff, $36
	.word @song1ref1339
	.byte $ff, $2f
	.word @song1ref1339
	.byte $c3
	.byte $ff, $36
	.word @song1ref1339
	.byte $ff, $2f
	.word @song1ref1339
	.byte $c3
	.byte $ff, $36
	.word @song1ref1339
	.byte $ff, $2f
	.word @song1ref1339
	.byte $c3, $b7
	.byte $ff, $46
	.word @song1ref1266
	.byte $ff, $46
	.word @song1ref1266
	.byte $5a, $99, $5a, $f9, $91, $5a, $f9, $e1, $fd
	.word @song1ch3loop
@song1ch4:
@song1ch4loop:
@song1ref1437:
	.byte $f9, $f9, $f9, $d1, $f9, $f9, $f9, $d1, $f9, $f9, $f9, $d1, $f9, $f9, $f9, $d1, $f9, $f9, $f9, $d1, $f9, $f9, $f9, $d1
	.byte $f9, $f9, $f9, $d1, $f9, $f9, $f9, $d1
	.byte $ff, $20
	.word @song1ref1437
	.byte $ff, $20
	.word @song1ref1437
	.byte $f9, $f9, $f9, $d1, $fd
	.word @song1ch4loop
@song2ch0:
	.byte $fb, $01
@song2ch0loop:
	.byte $f9, $f5, $f9, $f5, $f9, $f5, $f9, $f5, $f9, $f5, $f9, $f5, $f9, $f5, $f9, $f5, $8e, $44, $f5, $42, $f5, $3c, $e1, $90
	.byte $42, $87, $3c, $87, $8e, $3a, $cd, $42, $a5, $4a, $f5, $4e, $f5, $54, $cd, $58, $a5, $5a, $b9, $60, $b9, $44, $f5, $42
	.byte $f5, $3c, $e1, $90, $42, $87, $3c, $87, $8e, $3a, $cd, $42, $a5, $4a, $f5, $4e, $f5, $54, $cd, $58, $a5, $5a, $b9, $60
	.byte $b9, $f9, $b9, $5a, $b9, $5c, $f5, $5a, $cd, $5c, $91, $5a, $91, $44, $b9, $4a, $b9, $5a, $b9, $5c, $b9, $54, $b9, $5c
	.byte $a5, $5a, $87, $5c, $87, $5a, $b9, $60, $b9
@song2ref109:
	.byte $4a, $91, $2c, $87, $92, $22, $87, $8e, $32, $87, $92, $2c, $87, $8e, $3a, $87, $92, $32, $87, $8e, $44, $87, $92, $3a
	.byte $87, $8e, $4a, $87, $92, $44, $87, $8e, $48, $91, $2a, $87, $92, $22, $87, $8e, $30, $87, $92, $2a, $87, $8e, $3a, $87
	.byte $92, $30, $87, $8e, $42, $87, $92, $3a, $87, $8e, $48, $87, $92, $42, $87, $8e
	.byte $ff, $2c
	.word @song2ref109
@song2ref176:
	.byte $8e, $5c, $91, $4a, $87, $90, $5c, $87, $8e, $3a, $87, $90, $4a, $87, $8e, $44, $87, $90, $3a, $87, $8e, $4a, $87, $90
	.byte $44, $87, $8e, $52, $87, $90, $4a, $87, $8e, $5a, $91, $2a, $87, $90, $5a, $87, $8e, $30, $87, $92, $2a, $87, $8e, $42
	.byte $87, $92, $30, $87, $8e, $52, $87, $90, $42, $87, $8e, $5a, $87, $90, $52, $87
	.byte $ff, $2c
	.word @song2ref176
	.byte $8e
	.byte $ff, $2c
	.word @song2ref109
	.byte $8e
	.byte $ff, $2c
	.word @song2ref109
	.byte $ff, $2c
	.word @song2ref176
	.byte $ff, $2c
	.word @song2ref176
	.byte $8e
	.byte $ff, $2c
	.word @song2ref109
	.byte $8e
	.byte $ff, $2c
	.word @song2ref109
	.byte $ff, $2c
	.word @song2ref176
	.byte $ff, $2b
	.word @song2ref176
	.byte $85, $00, $f9, $f5, $f9, $f5, $f9, $f5, $f9, $f5, $fd
	.word @song2ch0loop
@song2ch1:
@song2ch1loop:
	.byte $00, $f9, $f3, $f9, $f5, $f9, $f5, $f9, $f5
@song2ref294:
	.byte $8e, $32, $91, $14, $87, $92, $0a, $87, $8e, $1a, $87, $92, $14, $87, $8e, $22, $87, $92, $1a, $87, $8e, $2c, $87, $92
	.byte $22, $87, $8e, $32, $87, $92, $2c, $87, $8e, $30, $91, $12, $87, $92, $0a, $87, $8e, $18, $87, $92, $12, $87, $8e, $22
	.byte $87, $92, $18, $87, $8e, $2a, $87, $92, $22, $87, $8e, $30, $87, $92, $2a, $87
	.byte $ff, $2c
	.word @song2ref294
@song2ref361:
	.byte $8e, $44, $91, $32, $87, $90, $44, $87, $8e, $22, $87, $90, $32, $87, $8e, $2c, $87, $90, $22, $87, $8e, $32, $87, $90
	.byte $2c, $87, $8e, $3a, $87, $90, $32, $87, $8e, $42, $91, $12, $87, $90, $42, $87, $8e, $18, $87, $92, $12, $87, $8e, $2a
	.byte $87, $92, $18, $87, $8e, $3a, $87, $90, $2a, $87, $8e, $42, $87, $90, $3a, $87
	.byte $ff, $2c
	.word @song2ref361
	.byte $ff, $2c
	.word @song2ref294
	.byte $ff, $2c
	.word @song2ref294
	.byte $ff, $2c
	.word @song2ref361
	.byte $ff, $2c
	.word @song2ref361
	.byte $ff, $2c
	.word @song2ref294
	.byte $ff, $2c
	.word @song2ref294
	.byte $ff, $2c
	.word @song2ref361
	.byte $ff, $2c
	.word @song2ref361
	.byte $00, $f9, $f3, $f9, $f5, $f9, $f5, $f9, $f5, $f9, $f5, $f9, $f5, $f9, $f5, $f9, $f5, $86, $2c, $91, $44, $91, $3a, $91
	.byte $44, $91, $48, $91, $4a, $91, $48, $b9, $42, $b9, $3c, $91, $24, $91, $3c, $91, $3c, $91, $44, $91, $3c, $91, $3a, $91
	.byte $2a, $91, $30, $91, $3a, $91, $42, $91, $48, $91, $4a, $91, $3a, $91, $44, $91, $4a, $91, $4e, $91, $52, $91, $4e, $b9
	.byte $4a, $b9, $4a, $91, $48, $91, $44, $91, $42, $91, $44, $91, $4a, $91, $48, $b9, $3a, $b9, $14, $91, $2c, $91, $22, $91
	.byte $2c, $91, $30, $91, $32, $91, $30, $b9, $2a, $b9, $24, $91, $0c, $91, $24, $91, $24, $91, $2c, $91, $24, $91, $22, $91
	.byte $12, $91, $18, $91, $22, $91, $2a, $8f, $00, $22, $8f, $00, $32, $91, $22, $91, $2c, $91, $32, $91, $36, $91, $3a, $91
	.byte $36, $b9, $32, $b9, $3c, $a5, $32, $91, $3c, $91, $40, $91, $3c, $91, $3a, $b9, $42, $b9, $8e, $44, $a5, $90, $44, $a5
	.byte $92, $44, $a5, $8e, $42, $a5, $90, $42, $a5, $92, $42, $a5, $8e, $44, $a5, $90, $44, $a5, $92, $44, $a5, $8e, $42, $a5
	.byte $90, $42, $a5, $92, $42, $a5, $8e, $44, $a5, $90, $44, $a5, $92, $44, $a5, $8e, $48, $a5, $90, $48, $a5, $92, $48, $a5
	.byte $8e, $4a, $a5, $90, $4a, $a5, $92, $4a, $a5, $8e, $42, $a5, $90, $42, $a5, $92, $42, $a5, $fd
	.word @song2ch1loop
@song2ch2:
@song2ch2loop:
@song2ref690:
	.byte $bb, $ae
@song2ref692:
	.byte $52, $91, $00, $e1, $52, $91, $00, $a5, $bb, $52, $91, $00, $e1, $58, $91, $00, $91, $52, $8f, $00, $bb, $52, $91, $00
	.byte $e1, $52, $91, $00, $a5, $bb, $52, $91, $00, $e1, $52, $8f, $00, $4a, $8f, $00, $42, $8f, $00, $bb
	.byte $ff, $2c
	.word @song2ref692
	.byte $ff, $2b
	.word @song2ref692
@song2ref742:
	.byte $b0
@song2ref743:
	.byte $44, $91, $5c, $91, $52, $91, $5c, $91, $60, $91, $62, $91, $60, $b9, $5a, $b9, $54, $91, $3c, $91, $54, $91, $54, $91
	.byte $5c, $91, $54, $91, $52, $91, $42, $91, $48, $91, $52, $91, $5a, $91, $60, $91, $62, $91, $52, $91, $5c, $91, $62, $91
	.byte $66, $91, $6a, $91, $66, $b9, $62, $b9, $ae, $62, $91, $b0, $60, $91, $5c, $91, $5a, $91, $5c, $91, $62, $91, $60, $b9
	.byte $52, $b7, $00
	.byte $ff, $24
	.word @song2ref743
@song2ref821:
	.byte $ae, $5a, $8f, $00, $52, $8f, $00, $b0, $62, $91, $52, $91, $5c, $91, $62, $91, $66, $91, $6a, $91, $66, $b9, $62, $b9
	.byte $6c, $a5, $62, $91, $6c, $91, $70, $91, $6c, $91, $6a, $b9, $72, $b5, $00, $81
	.byte $ff, $2d
	.word @song2ref690
	.byte $ff, $2b
	.word @song2ref692
	.byte $ff, $24
	.word @song2ref742
	.byte $ff, $26
	.word @song2ref821
	.byte $f9, $f5, $f9, $f5, $f9, $f5, $f9, $f5, $fd
	.word @song2ch2loop
@song2ch3:
@song2ch3loop:
	.byte $b0
@song2ref886:
	.byte $5c, $91, $8a, $58, $87, $00, $87, $58, $87, $00, $87, $b0, $44, $91, $8a, $58, $87, $00, $87, $58, $87, $00, $87, $b0
	.byte $5c, $91, $8a, $58, $87, $00, $87, $58, $87, $00, $87, $b0, $44, $91, $8a, $58, $87, $00, $87, $58, $87, $00, $87, $b0
	.byte $5c, $91, $8a, $58, $87, $00, $87, $58, $87, $00, $87, $b0, $44, $91, $8a, $58, $87, $00, $87, $58, $87, $00, $87, $b0
	.byte $5c, $91, $8a, $58, $87, $00, $87, $58, $87, $00, $87, $b0, $44, $91, $8a, $58, $85, $00, $58, $85, $00, $58, $87, $00
	.byte $87, $b0, $5c, $91, $8a, $58, $87, $00, $87, $58, $87, $00, $87, $b0, $44, $91, $8a, $58, $87, $00, $87, $58, $87, $00
	.byte $87, $b0, $4a, $91, $8a, $58, $87, $00, $87, $58, $87, $00, $87, $b0, $5e, $91, $5c, $91, $5a, $91, $54, $91, $8a, $58
	.byte $87, $00, $87, $58, $87, $00, $87, $b0, $52, $91, $8a, $58, $87, $00, $87, $58, $87, $00, $87, $b0, $4e, $91, $8a, $58
	.byte $87, $00, $87, $58, $87, $00, $87, $b0, $52, $8f, $00, $52, $8f, $00, $44, $8f, $00
	.byte $ff, $9d
	.word @song2ref886
	.byte $ff, $9d
	.word @song2ref886
	.byte $ff, $9d
	.word @song2ref886
	.byte $ff, $9d
	.word @song2ref886
	.byte $ff, $9d
	.word @song2ref886
	.byte $ff, $9d
	.word @song2ref886
	.byte $ff, $9d
	.word @song2ref886
	.byte $ff, $9d
	.word @song2ref886
	.byte $fd
	.word @song2ch3loop
@song2ch4:
@song2ch4loop:
@song2ref1099:
	.byte $02, $83, $0a, $8b, $12, $8f, $00, $0e, $8f, $00, $24, $83, $0a, $8b, $0c, $8f, $00, $0e, $8f, $00, $02, $83, $16, $8b
	.byte $1a, $8f, $00, $16, $8f, $00, $24, $83, $16, $8b, $14, $8f, $00, $16, $8f, $00, $02, $83, $08, $8b, $18, $8f, $00, $08
	.byte $8f, $00, $24, $83, $18, $8b, $08, $8f, $00, $08, $8f, $00, $02, $83, $16, $8b, $1a, $8f, $00, $0e, $8f, $00, $24, $83
	.byte $16, $8b, $14, $8f, $00, $0e, $8f, $00
	.byte $ff, $2a
	.word @song2ref1099
@song2ref1182:
	.byte $0c, $8b, $10, $8f, $00, $0c, $8f, $00, $12, $8f, $00, $10, $8f, $00, $12, $8f, $00, $02, $83, $1a, $8b, $16, $8f, $00
	.byte $14, $8f, $00, $1a, $8f, $00, $24, $91, $24, $91
	.byte $ff, $50
	.word @song2ref1099
	.byte $ff, $2a
	.word @song2ref1099
	.byte $ff, $22
	.word @song2ref1182
	.byte $ff, $50
	.word @song2ref1099
	.byte $ff, $2a
	.word @song2ref1099
	.byte $ff, $22
	.word @song2ref1182
	.byte $ff, $50
	.word @song2ref1099
	.byte $ff, $2a
	.word @song2ref1099
	.byte $ff, $22
	.word @song2ref1182
@song2ref1243:
	.byte $02, $83, $0a, $8b, $12, $8f, $00, $0a
@song2ref1251:
	.byte $8f, $00, $24, $83, $0a, $8b, $0a, $8f, $00, $12, $8f, $00, $02, $83, $16, $8b, $1a, $8f, $00, $16, $8f, $00, $24, $83
	.byte $16, $8b, $1a, $8f, $00, $16, $8f, $00, $02, $83, $08, $8b, $18, $8f, $00, $08, $8f, $00, $24, $83, $18, $8b, $08, $8f
	.byte $00, $08, $8f, $00, $02, $83, $16, $8b, $1a, $8f, $00, $1a, $8f, $00, $24, $83, $16, $8b, $1a, $8f, $00, $16, $8f, $00
	.byte $02, $83, $0a, $8b, $12, $8f, $00, $12
	.byte $ff, $22
	.word @song2ref1251
@song2ref1334:
	.byte $0c, $8b, $10, $8f, $00, $0c, $8f, $00, $0c, $8f, $00, $10, $8f, $00, $0c, $8f, $00, $02, $83, $1a, $8b, $16, $8f, $00
	.byte $1a, $8f, $00, $1a, $8f, $00, $02, $83, $1a, $89, $00, $1a, $8f, $00
	.byte $ff, $50
	.word @song2ref1099
	.byte $ff, $2a
	.word @song2ref1099
	.byte $ff, $22
	.word @song2ref1182
	.byte $ff, $50
	.word @song2ref1099
	.byte $ff, $2a
	.word @song2ref1099
	.byte $ff, $22
	.word @song2ref1182
	.byte $ff, $50
	.word @song2ref1099
	.byte $ff, $2a
	.word @song2ref1099
	.byte $ff, $22
	.word @song2ref1182
	.byte $ff, $58
	.word @song2ref1243
	.byte $ff, $22
	.word @song2ref1251
	.byte $ff, $26
	.word @song2ref1334
	.byte $fd
	.word @song2ch4loop
@song3ch0:
	.byte $fb, $01
@song3ch0loop:
	.byte $80
@song3ref5:
	.byte $52, $f9, $f9, $a9, $52, $f9, $f9, $a9, $58, $f9, $f9, $a9, $58, $f9, $f9, $a9
	.byte $ff, $10
	.word @song3ref5
	.byte $52, $f9, $f9, $a9, $58, $f9, $f9, $a9, $58, $f9, $f9, $a9
	.byte $ff, $10
	.word @song3ref5
	.byte $ff, $10
	.word @song3ref5
	.byte $ff, $10
	.word @song3ref5
@song3ref45:
	.byte $52, $f9, $f9, $a9
@song3ref49:
	.byte $4a, $f9, $f9, $a9, $52, $f9, $f9, $a9, $54, $f9, $f9, $a9, $54, $f9, $93, $58, $f9, $93
@song3ref67:
	.byte $52, $f9, $f9, $a9, $52, $f9, $f9, $a9, $52, $f9, $f9, $a9, $52, $f9, $f9, $a9
	.byte $ff, $10
	.word @song3ref67
	.byte $52, $f9, $f9, $a9, $58, $f9, $f9, $a9, $58, $f9, $f9, $a9
	.byte $ff, $10
	.word @song3ref5
	.byte $ff, $16
	.word @song3ref45
	.byte $ff, $12
	.word @song3ref49
	.byte $fd
	.word @song3ch0loop
@song3ch1:
@song3ch1loop:
	.byte $80
@song3ref112:
	.byte $4a, $f9, $f9, $a9, $4a, $f9, $f9, $a9, $52, $f9, $f9, $a9, $52, $f9, $f9, $a9
	.byte $ff, $10
	.word @song3ref112
@song3ref131:
	.byte $4a, $f9, $f9, $a9, $4e, $f9, $f9, $a9, $4e, $f9, $f9, $a9, $4a, $f9, $93, $48, $f9, $93
	.byte $ff, $12
	.word @song3ref131
	.byte $ff, $12
	.word @song3ref131
	.byte $ff, $12
	.word @song3ref131
@song3ref158:
	.byte $44, $f9, $f9, $a9, $4a, $f9, $f9, $a9, $4a, $f9, $f9, $a9, $4a, $f9, $93, $4e, $f9, $93
@song3ref176:
	.byte $4a, $f9, $f9, $a9, $4a, $f9, $f9, $a9, $48, $f9, $f9, $a9, $48, $f9, $f9, $a9
	.byte $ff, $10
	.word @song3ref176
	.byte $ff, $12
	.word @song3ref131
	.byte $ff, $12
	.word @song3ref131
	.byte $ff, $12
	.word @song3ref158
	.byte $ff, $12
	.word @song3ref158
	.byte $fd
	.word @song3ch1loop
@song3ch2:
@song3ch2loop:
	.byte $80, $14, $f9, $f9, $a9, $14, $f9, $f9, $a9, $1a, $f9, $f9, $a9, $1a, $f9, $f9, $a9, $14, $f9, $f9, $a9, $14, $f9, $f9
	.byte $a9, $02, $f9, $f9, $a9, $02, $f9, $f9, $a9
@song3ref244:
	.byte $0c, $f9, $f9, $a9, $18, $f9, $f9, $a9, $0a, $f9, $f9, $a9, $14, $f9, $93, $10, $f9, $93
	.byte $ff, $12
	.word @song3ref244
	.byte $ff, $12
	.word @song3ref244
	.byte $ff, $12
	.word @song3ref244
@song3ref271:
	.byte $06, $f9, $f9, $a9, $0a, $f9, $f9, $a9, $0c, $f9, $f9, $a9, $10, $f9, $f9, $a9
@song3ref287:
	.byte $14, $8f, $14, $8f, $14, $8f, $14, $8f, $14, $8f, $14, $8f, $14, $8f, $14, $8f
	.byte $ff, $10
	.word @song3ref287
	.byte $ff, $10
	.word @song3ref287
	.byte $ff, $10
	.word @song3ref287
@song3ref312:
	.byte $02, $8f, $02, $8f, $02, $8f, $02, $8f, $02, $8f, $02, $8f, $02, $8f, $02, $8f
	.byte $ff, $10
	.word @song3ref312
	.byte $ff, $10
	.word @song3ref312
	.byte $ff, $10
	.word @song3ref312
	.byte $ff, $10
	.word @song3ref287
	.byte $ff, $10
	.word @song3ref287
	.byte $ff, $10
	.word @song3ref287
	.byte $ff, $10
	.word @song3ref287
	.byte $ff, $10
	.word @song3ref312
	.byte $ff, $10
	.word @song3ref312
	.byte $ff, $10
	.word @song3ref312
	.byte $ff, $10
	.word @song3ref312
@song3ref361:
	.byte $0c, $8f, $0c, $8f, $0c, $8f, $0c, $8f, $0c, $8f, $0c, $8f, $0c, $8f, $0c, $8f
	.byte $ff, $10
	.word @song3ref361
@song3ref380:
	.byte $18, $8f, $18, $8f, $18, $8f, $18, $8f, $18, $8f, $18, $8f, $18, $8f, $18, $8f
	.byte $ff, $10
	.word @song3ref380
@song3ref399:
	.byte $0a, $8f, $0a, $8f, $0a, $8f, $0a, $8f, $0a, $8f, $0a, $8f, $0a, $8f, $0a, $8f
	.byte $ff, $10
	.word @song3ref399
	.byte $ff, $10
	.word @song3ref287
@song3ref421:
	.byte $10, $8f, $10, $8f, $10, $8f, $10, $8f, $10, $8f, $10, $8f, $10, $8f, $10, $8f
	.byte $ff, $10
	.word @song3ref361
	.byte $ff, $10
	.word @song3ref361
	.byte $ff, $10
	.word @song3ref380
	.byte $ff, $10
	.word @song3ref380
	.byte $ff, $10
	.word @song3ref399
	.byte $ff, $10
	.word @song3ref399
	.byte $ff, $10
	.word @song3ref287
	.byte $ff, $10
	.word @song3ref421
@song3ref461:
	.byte $06, $8f, $06, $8f, $06, $8f, $06, $8f, $06, $8f, $06, $8f, $06, $8f, $06, $8f
	.byte $ff, $10
	.word @song3ref461
	.byte $ff, $10
	.word @song3ref399
	.byte $ff, $10
	.word @song3ref399
	.byte $ff, $10
	.word @song3ref361
	.byte $ff, $10
	.word @song3ref361
	.byte $ff, $10
	.word @song3ref421
	.byte $ff, $10
	.word @song3ref421
	.byte $ff, $10
	.word @song3ref271
	.byte $fd
	.word @song3ch2loop
@song3ch3:
@song3ch3loop:
@song3ref505:
	.byte $f9, $f9, $ab, $f9, $f9, $ab, $f9, $f9, $ab, $f9, $f9, $ab, $f9, $f9, $ab, $f9, $f9, $ab
	.byte $ff, $12
	.word @song3ref505
	.byte $ff, $12
	.word @song3ref505
	.byte $ff, $12
	.word @song3ref505
	.byte $f9, $f9, $ab, $f9, $f9, $ab, $f9, $f9, $ab, $f9, $f9, $ab
@song3ref544:
	.byte $a0, $4c, $8f, $88, $52, $8f, $ac, $52, $a1, $a2, $4c, $8f, $88, $4c, $8f, $ac, $4c, $8f, $a0, $4c, $8f, $88, $4c, $8f
	.byte $a0, $4c, $8f, $4c, $8f, $88, $4c, $8f, $a2, $4c, $8f, $88, $4c, $8f, $ac, $4c, $a1
	.byte $ff, $1c
	.word @song3ref544
	.byte $ff, $1c
	.word @song3ref544
	.byte $ff, $1c
	.word @song3ref544
	.byte $ff, $1c
	.word @song3ref544
	.byte $ff, $1c
	.word @song3ref544
	.byte $ff, $1c
	.word @song3ref544
	.byte $ff, $1c
	.word @song3ref544
	.byte $ff, $1c
	.word @song3ref544
	.byte $ff, $1c
	.word @song3ref544
	.byte $ff, $1c
	.word @song3ref544
	.byte $ff, $1c
	.word @song3ref544
	.byte $ff, $1c
	.word @song3ref544
	.byte $ff, $1c
	.word @song3ref544
	.byte $ff, $1c
	.word @song3ref544
	.byte $ff, $1c
	.word @song3ref544
	.byte $ff, $1c
	.word @song3ref544
	.byte $ff, $1c
	.word @song3ref544
	.byte $ff, $1c
	.word @song3ref544
	.byte $ff, $1c
	.word @song3ref544
@song3ref642:
	.byte $91, $88, $48, $8f, $ac, $4c, $a1, $88, $48, $8f, $48, $8f, $ac, $48, $b3, $88, $48, $8f, $ac, $4c, $a1, $88, $48, $8f
	.byte $48, $8f, $ac, $48, $a1
	.byte $ff, $15
	.word @song3ref642
	.byte $ff, $15
	.word @song3ref642
	.byte $ff, $15
	.word @song3ref642
	.byte $fd
	.word @song3ch3loop
@song3ch4:
@song3ch4loop:
	.byte $ff, $12
	.word @song3ref505
	.byte $ff, $12
	.word @song3ref505
	.byte $ff, $12
	.word @song3ref505
	.byte $ff, $12
	.word @song3ref505
	.byte $f9, $f9, $ab, $f9, $f9, $ab, $f9, $f9, $ab, $f9, $f9, $ab
@song3ref708:
	.byte $1e, $8f, $04, $8f, $20, $a1, $22, $8f, $04, $8f, $20, $8f, $1e, $8f, $04, $8f, $1e, $8f, $1e, $8f, $04, $8f, $22, $8f
	.byte $04, $8f, $20, $a1
	.byte $ff, $1c
	.word @song3ref708
	.byte $ff, $1c
	.word @song3ref708
	.byte $ff, $1c
	.word @song3ref708
	.byte $ff, $1c
	.word @song3ref708
	.byte $ff, $1c
	.word @song3ref708
	.byte $ff, $1c
	.word @song3ref708
	.byte $ff, $1c
	.word @song3ref708
	.byte $ff, $1c
	.word @song3ref708
	.byte $ff, $1c
	.word @song3ref708
	.byte $ff, $1c
	.word @song3ref708
	.byte $ff, $1c
	.word @song3ref708
	.byte $ff, $1c
	.word @song3ref708
	.byte $ff, $1c
	.word @song3ref708
	.byte $ff, $1c
	.word @song3ref708
	.byte $ff, $1c
	.word @song3ref708
	.byte $ff, $1c
	.word @song3ref708
	.byte $ff, $1c
	.word @song3ref708
	.byte $ff, $1c
	.word @song3ref708
	.byte $ff, $1c
	.word @song3ref708
@song3ref793:
	.byte $91, $04, $8f, $20, $a1, $04, $8f, $06, $8f, $20, $b3, $04, $8f, $20, $a1, $04, $8f, $06, $8f, $20, $a1
	.byte $ff, $15
	.word @song3ref793
	.byte $ff, $15
	.word @song3ref793
	.byte $ff, $15
	.word @song3ref793
	.byte $fd
	.word @song3ch4loop
@song4ch0:
	.byte $fb, $01
@song4ch0loop:
	.byte $9a, $44, $d1, $9b, $52, $f9, $c7
@song4ref11:
	.byte $52, $8b, $58, $8b, $52, $8b, $4e, $8b, $52, $ed, $52, $8b, $58, $8b, $52, $8b, $4e, $8b, $52, $ed, $52, $8b, $58, $8b
	.byte $52, $8b, $4e, $8b, $52, $8b, $58, $8b, $52, $8b, $4e, $8b, $52, $99, $2c, $85, $00, $83, $14, $8b, $9c, $2c, $8b, $9a
	.byte $14, $85, $00, $83, $14, $93, $00, $83, $9c, $2c, $8b, $9a, $24, $85, $00, $83, $22, $8b, $24, $8b, $9c, $2c, $8b, $9a
	.byte $24, $8b, $22, $85, $00, $83, $1a, $85, $00, $83, $9c, $2c, $8b, $9a, $1a, $8b, $32, $85, $00, $83, $1a, $8b, $9c, $2c
	.byte $8b, $9a, $1a, $85, $00, $83, $1a, $93, $00, $83, $9c, $2c, $8b, $9a, $1e, $8b, $28, $85, $00, $83, $1e, $8b, $9c, $2c
	.byte $8b, $9a, $1e, $85, $00, $83, $1a, $8b, $1e, $85, $00, $83, $44, $ed, $52, $c3, $52, $a7, $5c, $ed, $72, $b5, $72, $b5
@song4ref155:
	.byte $96, $44, $8b, $3a, $8b, $44, $8b, $32, $8b, $36, $8b, $32, $8b, $44, $8b, $9a, $4a, $8b, $96, $44, $8b, $9a, $4e, $8b
	.byte $52, $8b, $4e, $8b, $58, $8b, $94, $52, $8b, $9a, $58, $8b, $94, $5c, $8b, $58, $8b, $5c, $8b, $4e, $8b, $96, $52, $8b
	.byte $94, $4e, $8b, $96, $58, $8b, $62, $8b, $58, $8b, $62, $8b, $9a, $66, $8b, $96, $62, $8b, $9a, $62, $8b, $60, $8b, $62
	.byte $8b, $60, $8b, $00, $8b
	.byte $ff, $2a
	.word @song4ref155
@song4ref235:
	.byte $96, $4e, $8b, $4a, $8b, $4e, $8b, $42, $8b, $9a, $48, $8b, $96, $42, $8b, $9a, $52, $8b, $4a, $8b, $52, $8b, $4a
@song4ref258:
	.byte $8b, $00, $8b, $96
@song4ref262:
	.byte $5c, $8b, $52, $8b, $5c, $8b, $4a, $8b, $4e, $8b, $4a, $8b, $5c, $8b, $9a, $62, $8b, $96, $5c, $8b, $9a, $66, $8b, $6a
	.byte $8b, $66, $8b, $70, $8b, $94, $6a, $8b, $9a, $70, $8b, $94, $74, $8b, $70, $8b, $74, $8b, $66, $8b, $96, $6a, $8b, $94
	.byte $66, $8b, $96, $70, $8b, $7a, $8b, $70, $8b, $7a, $8b, $9a, $7e, $8b, $96, $7a, $8b, $9a, $7a, $8b, $78, $8b, $7a, $8b
	.byte $78
	.byte $ff, $2d
	.word @song4ref258
	.byte $96, $66, $8b, $62, $8b, $66, $8b, $5a, $8b, $9a, $62, $8b, $96, $5a, $8b, $9a, $66, $8b, $62, $8b, $66, $8b, $62
@song4ref361:
	.byte $8b, $00, $8b, $96
@song4ref365:
	.byte $5c, $a7, $62, $85, $5c, $83, $62, $99, $6a, $85, $62, $83, $6a, $8b, $74, $ed, $9a, $70, $99, $70, $8b, $6a, $99, $6a
@song4ref389:
	.byte $8b, $62, $99, $60, $ed, $96
@song4ref395:
	.byte $52, $a1, $00, $83, $4e, $a1, $00, $83, $4a, $99, $42, $a1, $00, $83, $4a, $a1, $00, $83, $4e, $99, $50, $89, $00, $8d
@song4ref419:
	.byte $50, $89, $00, $4e, $89, $00, $8d, $4e, $89, $00, $4a, $89, $00, $8d, $48, $b5, $4a, $99, $4a, $99
	.byte $ff, $14
	.word @song4ref365
	.byte $68, $99, $68
	.byte $ff, $2b
	.word @song4ref389
	.byte $4a, $c3, $4a, $99, $00, $8b
	.byte $ff, $3d
	.word @song4ref262
	.byte $8b, $00, $8b
	.byte $ff, $2a
	.word @song4ref155
	.byte $ff, $16
	.word @song4ref235
@song4ref466:
	.byte $96, $58, $8b, $4e, $8b, $58, $8b, $46, $8b, $4a, $8b, $46, $8b, $58, $8b, $9a, $5e, $8b, $96, $58, $8b, $9a, $62, $8b
	.byte $66, $8b, $62, $8b, $6c, $8b, $94, $66, $8b, $9a, $6c, $8b, $94, $70, $8b, $6c, $8b, $70, $8b, $62, $8b, $96, $66, $8b
	.byte $94, $62, $8b, $96, $6c, $8b, $76, $8b, $6c, $8b, $76, $8b, $9a, $7a, $8b, $96, $76, $8b, $9a, $76, $8b, $74, $8b, $76
	.byte $8b, $74, $8b, $00, $8b
	.byte $ff, $2a
	.word @song4ref466
	.byte $96, $62, $8b, $5e, $8b, $62, $8b, $56, $8b, $9a, $5e, $8b, $96, $56, $8b, $9a, $62, $8b, $5e, $8b, $62, $8b, $5e, $8b
	.byte $00, $8b, $58, $85, $00, $83, $4e, $85, $00, $83, $5c, $8b, $5e, $8b, $4e, $8b, $4e, $8b, $70, $8b, $70, $8b, $6c, $85
	.byte $00, $83, $62, $85, $00, $83, $5e, $8b, $5c, $8b, $54, $8b, $4a, $85, $00, $83, $54, $85, $00, $83, $58, $8b, $5e, $8b
	.byte $5e, $8b, $62, $8b, $62, $8b, $66, $8b, $62, $8b, $5e, $85, $00, $83, $58, $85, $00, $83, $5e, $8b, $62, $8b, $58, $8b
	.byte $58, $8b, $3c, $8b, $40, $8b, $3c, $8b, $3c, $8b, $96, $36, $85, $00, $83, $3c, $85, $36, $83, $40, $85, $3c, $83, $46
	.byte $85, $40, $83, $44, $85, $46, $8b, $44, $83, $4a, $85, $46, $83, $4e, $85, $4a, $83, $46, $85, $4e, $8b, $46, $83, $54
	.byte $85, $4e, $83, $58, $85, $54, $83, $4e, $85, $58, $8b, $4e, $83, $5c, $85, $58, $83, $5e, $85, $5c, $83, $66, $8b, $6c
	.byte $8b, $5e, $8b, $54, $8b, $70, $8b, $70, $8b, $58, $8b, $40, $85, $58, $83, $56, $85, $58, $8b, $56, $8b, $58, $8b, $56
	.byte $8b, $58, $8b, $56, $83, $5c, $85, $58, $83, $5e, $8b, $9a, $5e, $8b, $62, $8b, $5e, $8b, $66, $8b, $58, $8b, $66, $8b
	.byte $5e, $8b, $62, $8b, $66, $8b, $58, $8b, $66, $8b, $96, $70, $a7, $9a, $70, $99, $96, $76, $99, $76, $99, $74, $99, $74
	.byte $99, $70, $8b, $66, $8b, $70, $8b, $5c, $a7, $5c, $99, $9a, $46, $8b, $4a, $8b, $46, $8b, $4e, $8b, $40, $8b, $4e, $8b
	.byte $46, $8b, $4a, $8b, $4e, $8b, $40, $8b, $4e, $8b, $96, $40, $a7, $9a, $40, $99, $4a, $8b, $96, $4a, $8b, $94, $4a, $8b
	.byte $96, $4a, $8b, $9a, $44, $8b, $96, $44, $8b, $94, $44, $8b, $96, $44, $8b, $9a, $44, $8b, $96, $44, $8b, $94, $44, $8b
	.byte $96, $44, $8b, $9a, $3e, $8b, $96, $3e, $8b, $94, $3e, $8b, $96, $3e, $8b, $9a, $76, $8b, $7a, $8b, $76, $8b, $7e, $8b
	.byte $70, $8b, $7e, $8b, $76, $8b, $7a, $8b, $7e, $8b, $70, $8b, $7e, $8b, $96, $08, $a7, $9a, $08, $99, $96, $0e, $99, $0e
	.byte $99, $0c, $99, $0c, $99, $08, $8b, $7e, $8b, $08, $8b, $74, $a7, $74, $99, $9a, $2e, $8b, $32, $8b, $2e, $8b, $36, $8b
	.byte $28, $8b, $36, $8b, $2e, $8b, $32, $8b, $36, $8b, $28, $8b, $36, $8b, $96, $28, $a7, $9a, $28, $99, $2c, $8b, $96, $2c
	.byte $8b, $94, $2c, $8b, $96, $2c, $8b, $9a, $2e, $8b, $96, $2e, $8b, $94, $2e, $8b, $96, $2e, $8b, $9a, $32, $8b, $96, $32
	.byte $8b, $94, $32, $8b, $96, $32, $8b, $9a, $34, $8b, $96, $34, $8b, $94, $34, $8b, $96, $34, $8b, $9a, $36, $8b, $96, $36
	.byte $8b, $94, $36, $8b, $96, $36, $8b, $9a, $38, $8b, $96, $38, $8b, $94, $38, $8b, $96, $38, $8b, $9a, $3a, $8b, $96, $3a
	.byte $8b, $94, $3a, $8b, $96, $3a, $8b, $9a, $3e, $8b, $96, $3e, $8b, $94, $3e, $8b, $96, $3e, $8b, $52, $8b, $48, $8b, $52
	.byte $8b, $40, $8b, $44, $8b, $40, $8b, $52, $8b, $9a, $58, $8b, $96, $52, $8b, $9a, $5c, $8b, $60, $8b, $5c, $8b, $66, $8b
	.byte $94, $60, $8b, $9a, $66, $8b, $94, $6a, $8b, $66, $8b, $6a, $8b, $5c, $8b, $96, $60, $8b, $94, $5c, $8b, $96, $66, $8b
	.byte $70, $8b, $66, $8b, $70, $8b, $9a, $74, $8b, $96, $70, $8b, $9a, $70, $8b, $6e, $8b, $70, $8b, $6e, $8b, $00, $8b, $96
	.byte $3a, $8b, $30, $8b, $3a, $8b, $28, $8b, $2c, $8b, $28, $8b, $3a, $8b, $9a, $40, $8b, $96, $3a, $8b, $9a, $44, $8b, $48
	.byte $8b, $44, $8b, $4e, $8b, $94, $48, $8b, $9a, $4e, $8b, $94, $52, $8b, $4e, $8b, $52, $8b, $44, $8b, $96, $48, $8b, $94
	.byte $44, $8b, $96, $44, $8b, $40, $8b, $44, $8b, $38, $8b, $9a, $3e, $8b, $96, $38, $8b, $9a, $48, $8b, $40, $8b, $48, $8b
	.byte $40
@song4ref1195:
	.byte $8b, $00, $8b, $96, $56, $8b, $4c, $8b, $56, $8b, $44, $8b, $48, $8b, $44, $8b, $56, $8b, $9a, $5c, $8b, $96, $56, $8b
	.byte $9a, $60, $8b, $64, $8b, $60, $8b, $6a, $8b, $94, $64, $8b, $9a, $6a, $8b, $94, $6e, $8b, $6a, $8b, $6e, $8b, $60, $8b
	.byte $96, $64, $8b, $94, $60, $8b, $96, $6a, $8b, $74, $8b, $6a, $8b, $74, $8b, $9a, $78, $8b, $96, $74, $8b, $9a, $74, $8b
	.byte $72, $8b, $74, $8b, $72
	.byte $ff, $2d
	.word @song4ref1195
	.byte $96, $60, $8b, $5c, $8b, $60, $8b, $54, $8b, $9a, $5c, $8b, $96, $54, $8b, $9a, $60, $8b, $5c, $8b, $60, $8b, $5c
	.byte $ff, $34
	.word @song4ref361
	.byte $8b, $00, $8b
	.byte $ff, $14
	.word @song4ref419
	.byte $ff, $14
	.word @song4ref365
	.byte $68, $99, $68
	.byte $ff, $31
	.word @song4ref389
	.byte $ff, $2c
	.word @song4ref395
	.byte $ff, $14
	.word @song4ref395
@song4ref1322:
	.byte $52, $8b, $58, $8b, $5c, $8b, $52, $8b, $62, $8b, $66, $8b, $70, $8b, $7e, $8b, $74, $b5, $74, $b5, $f5, $02, $cb, $00
	.byte $99, $fd
	.word @song4ch0loop
@song4ch1:
@song4ch1loop:
	.byte $b7, $9a, $44, $99, $d3, $52, $df, $00, $a7, $b7, $52, $8b, $58, $8b, $52, $8b, $4e, $8b, $52, $df, $00, $8b
	.byte $ff, $12
	.word @song4ref11
	.byte $44, $99, $96
@song4ref1379:
	.byte $2c, $85, $00, $83, $14, $8b, $98, $2c, $8b, $96, $14, $85, $00, $83, $14, $93, $00, $83, $98, $2c, $8b, $96, $24, $85
	.byte $00, $83, $22, $8b, $24, $8b, $98, $2c, $8b, $96, $24, $8b, $22, $85, $00, $83, $1a, $85, $00, $83, $98, $2c, $8b, $96
	.byte $1a, $8b, $32, $85, $00, $83, $1a, $8b, $98, $2c, $8b, $96, $1a, $85, $00, $83, $1a, $93, $00, $83, $98, $2c, $8b, $96
	.byte $1e, $8b, $28, $85, $00, $83, $1e, $8b, $98, $2c, $8b, $96, $1e, $85, $00, $83, $1a, $8b, $1e, $85, $00, $83, $98, $2c
	.byte $8b, $96, $14, $8b
	.byte $ff, $26
	.word @song4ref1379
	.byte $52, $ed, $60, $b5, $60, $b5
@song4ref1488:
	.byte $9a, $3a, $8b, $32, $89, $00, $3a, $89, $00, $2c, $89, $00, $30, $89, $00, $2c, $89, $00, $3c, $89, $00, $44, $89, $00
	.byte $3c
@song4ref1513:
	.byte $89, $00
@song4ref1515:
	.byte $48, $89, $00, $4a, $89, $00, $48, $89, $00, $52, $89, $00, $4a, $89, $00, $52, $89, $00, $54, $89, $00, $52, $89, $00
	.byte $54
	.byte $ff, $0e
	.word @song4ref1513
@song4ref1543:
	.byte $5c, $89, $00, $52, $89, $00, $5c, $89, $00, $60
@song4ref1553:
	.byte $89, $00, $5c, $89, $00, $5c, $89, $00, $58, $89, $00, $5c, $89, $00, $58, $89, $00, $8d, $3a, $8b, $32, $8b, $3a, $8b
	.byte $2c, $8b, $30, $8b, $2c, $8b, $3c, $8b, $44, $8b, $3c, $8b
	.byte $ff, $19
	.word @song4ref1515
	.byte $89, $00, $48, $89, $00, $4a, $89, $00, $48, $89, $00, $48, $89, $00, $44, $89, $00, $48, $89, $00, $3a, $89, $00, $42
	.byte $89, $00, $3a, $89, $00, $48, $89, $00, $42, $89, $00, $48, $89, $00, $42
@song4ref1631:
	.byte $89, $00, $8d, $52, $89, $00, $4a, $89, $00, $52, $89, $00, $44, $89, $00, $48, $89, $00, $44, $89, $00, $54, $89, $00
	.byte $5c, $89, $00, $54, $89, $00, $60, $89, $00, $62, $89, $00, $60, $8b, $6a, $8b, $62, $8b, $6a, $8b, $6c, $8b, $6a, $8b
	.byte $6c, $8b, $60, $8b, $62, $89, $00, $60, $89, $00, $6a, $8b, $74, $89, $00, $6a, $89, $00, $74, $89, $00, $78, $89, $00
	.byte $74, $89, $00, $74, $89, $00, $70, $89, $00, $74, $89, $00, $70
	.byte $ff, $25
	.word @song4ref1631
@song4ref1719:
	.byte $89, $00, $6a, $89, $00, $62, $89, $00, $6a, $89, $00, $6c, $89, $00, $6a, $89, $00, $6c, $89, $00, $60, $89, $00, $62
	.byte $89, $00, $60, $89, $00, $60, $89, $00, $5c, $8b, $60, $8b, $54, $8b, $5a, $8b, $54, $8b, $60, $8b, $5a, $8b, $60, $8b
	.byte $5a
@song4ref1768:
	.byte $89, $00, $8d, $96
@song4ref1772:
	.byte $2c, $85, $00, $83, $2c, $99, $32, $85, $2c, $83, $32, $99, $3a, $85, $32, $83, $3a, $8b, $9a, $3c, $b5, $4a, $85, $3c
	.byte $83, $4a, $a7, $96, $52, $a7, $4a, $a7, $58, $a1, $00, $83, $4e, $85, $58, $83, $48, $85, $4e, $83, $40, $85, $48, $83
	.byte $36, $85, $40, $83, $30, $85, $36, $83, $28, $85, $30, $83, $1e, $85, $28
@song4ref1835:
	.byte $83
@song4ref1836:
	.byte $44, $8b, $52, $8b, $44, $85, $00, $83, $3e, $8b, $4e, $8b, $3e, $85, $00, $83, $3a, $99, $3c, $8b, $42, $8b, $3c, $85
	.byte $00, $83, $42, $8b, $4a, $8b, $42, $85, $00, $83, $46, $99, $40, $89, $00, $8d, $40, $89, $00, $3e, $89, $00, $8d
@song4ref1883:
	.byte $3e, $89, $00, $38, $89, $00, $8d, $40, $b5, $44, $99, $44, $99
	.byte $ff, $1a
	.word @song4ref1772
@song4ref1899:
	.byte $96, $50, $99, $52, $8b, $4a, $a7, $58, $99, $1e, $85, $00, $83, $24, $85, $1e, $83, $30, $85, $24, $83, $36, $85, $30
	.byte $83, $40, $85, $36, $83, $48, $85, $40, $83, $4e, $85, $48, $83, $58, $85, $4e
	.byte $ff, $37
	.word @song4ref1835
	.byte $44, $c3, $44, $99, $00, $8b
	.byte $ff, $33
	.word @song4ref1488
	.byte $ff, $0e
	.word @song4ref1513
	.byte $ff, $1c
	.word @song4ref1543
	.byte $96, $52, $89, $00, $4a, $89, $00, $52, $8b, $44, $8b, $48, $8b, $44, $8b, $54, $8b, $5c, $8b, $54, $8b, $60, $8b, $62
	.byte $89, $00, $60
	.byte $ff, $21
	.word @song4ref1719
	.byte $89, $00, $60, $89, $00, $52, $89, $00, $5a, $89, $00, $52, $89, $00, $60, $89, $00, $5a, $89, $00, $60, $89, $00, $5a
@song4ref2011:
	.byte $89, $00, $8d, $4e, $89, $00, $46, $89, $00, $4e, $89, $00, $40, $89, $00, $44, $89, $00, $40, $89, $00, $50, $89, $00
	.byte $58, $89, $00, $50, $89, $00, $5c, $89, $00, $5e, $89, $00, $5c, $89, $00, $66, $89, $00, $5e, $8b, $66, $8b, $68, $8b
	.byte $66, $8b, $68, $8b, $5c, $8b, $5e, $8b, $5c, $8b, $66, $8b, $70, $89, $00, $66, $89, $00, $70, $89, $00, $74, $89, $00
	.byte $70, $89, $00, $70, $89, $00, $6c, $89, $00, $70, $89, $00, $6c
	.byte $ff, $2b
	.word @song4ref2011
	.byte $89, $00, $66, $89, $00, $68, $89, $00, $66, $89, $00, $68, $89, $00, $5c, $89, $00, $5e
	.byte $ff, $0e
	.word @song4ref1553
	.byte $50, $8b, $56, $8b, $50, $8b, $5c, $8b, $56, $8b, $5c, $8b, $56, $8b, $00, $8b, $1e, $8b, $28, $85, $1e, $83, $28, $8b
	.byte $36, $99, $40, $85, $36, $83, $40, $8b, $4e, $85, $40, $83, $1a, $8b, $24, $85, $1a, $83, $24, $8b, $32, $99, $3c, $85
	.byte $32, $83, $3c, $8b, $4a, $85, $3c, $83, $10, $8b, $1a, $85, $10, $83, $1a, $8b, $28, $99, $32, $85, $28, $83, $32, $8b
	.byte $40, $85, $32, $83, $36, $8b, $38, $8b, $36, $8b, $36, $8b, $9a, $4e, $8b, $4e, $8b, $36, $99, $b7, $36, $8b, $3c, $8b
	.byte $40, $8b, $3c, $8b, $32, $b5, $32, $8b, $36, $8b, $32, $8b, $2e, $8b, $5e, $8b, $66, $8b, $54, $8b, $4e, $8b, $66, $8b
	.byte $66, $8b, $4e, $8b, $36, $85, $4e, $8b, $52, $8b, $4e, $8b, $52, $8b, $4e, $8b, $52, $8b, $4e, $83, $56, $85, $52, $83
	.byte $58, $8b, $96, $58, $8b, $5c, $8b, $58, $8b, $5c, $8b, $4e, $8b, $5e, $8b, $94, $58, $8b, $5c, $8b, $5e, $8b, $4e, $8b
	.byte $5e, $8b, $66, $85, $4e, $83, $66, $99, $96, $66, $99, $70, $99, $70, $99, $6c, $99, $6c, $99, $68, $8b, $5c, $8b, $68
	.byte $8b, $56, $a7, $56, $99, $40, $8b, $44, $8b, $40, $8b, $44, $8b, $36, $8b, $46, $8b, $94, $40, $8b, $44, $8b, $46, $8b
	.byte $36, $8b, $46, $8b, $36, $85, $1e, $83, $36, $99, $96, $36, $99, $9a, $3c, $8b, $96, $3c, $8b, $94, $3c, $8b, $96, $3c
	.byte $8b, $9a, $36, $8b, $96, $36, $8b, $94, $36, $8b, $96, $36, $8b, $9a, $3e, $8b, $96, $3e, $8b, $94, $3e, $8b, $96, $3e
	.byte $8b, $9a, $36, $8b, $96, $36, $8b, $94, $36, $8b, $96, $36, $8b, $70, $8b, $74, $8b, $70, $8b, $74, $8b, $66, $8b, $76
	.byte $8b, $94, $70, $8b, $74, $8b, $76, $8b, $66, $8b, $76, $8b, $7e, $85, $66, $83, $7e, $99, $96, $7e, $99, $08, $99, $08
	.byte $99, $02, $99, $02, $99, $00, $8b, $74, $8b, $00, $8b, $6e, $a7, $6e, $99, $28, $8b, $2c, $8b, $28, $8b, $2c, $8b, $1e
	.byte $8b, $2e, $8b, $94, $28, $8b, $2c, $8b, $2e, $8b, $1e, $8b, $2e, $8b, $1e, $85, $06, $83, $1e, $99, $96, $1e, $99, $9a
	.byte $1e, $8b, $96, $1e, $8b, $94, $1e, $8b, $96, $1e, $8b, $9a, $20, $8b, $96, $20, $8b, $94, $20, $8b, $96, $20, $8b, $9a
	.byte $24, $8b, $96, $24, $8b, $94, $24, $8b, $96, $24, $8b, $9a, $26, $8b, $96, $26, $8b, $94, $26, $8b, $96, $26, $8b, $9a
	.byte $28, $8b, $96, $28, $8b, $94, $28, $8b, $96, $28, $8b, $9a, $2a, $8b, $96, $2a, $8b, $94, $2a, $8b, $96, $2a, $8b, $9a
	.byte $2c, $8b, $96, $2c, $8b, $94, $2c, $8b, $96, $2c, $8b, $9a, $30, $8b, $96, $30, $8b, $94, $30, $8b, $96, $30, $8b, $9a
	.byte $30, $8b, $28, $8b, $30, $8b, $22, $8b, $26, $8b, $22, $8b, $32, $8b, $3a, $89, $00, $32
@song4ref2594:
	.byte $89, $00, $3e, $89, $00, $40, $89, $00, $3e, $89, $00, $48, $89, $00, $40, $89, $00, $48, $89, $00, $4a, $89, $00, $48
	.byte $89, $00, $4a
	.byte $ff, $0e
	.word @song4ref2594
	.byte $52, $89, $00, $48, $89, $00, $52, $89, $00, $56, $89, $00, $52, $89, $00, $52, $89, $00, $4e, $89, $00, $52, $89, $00
	.byte $4e, $89, $00, $8d, $48, $89, $00, $40, $89, $00, $48, $89, $00, $3a, $89, $00, $3e, $89, $00, $3a, $89, $00, $4a, $89
	.byte $00, $52, $89, $00, $4a, $89, $00, $56, $89, $00, $58, $89, $00, $56, $8b, $60, $8b, $58, $8b, $60, $8b, $62, $8b, $60
	.byte $8b, $62, $8b, $56, $8b, $58, $89, $00, $56, $89, $00, $56, $89, $00, $52, $89, $00, $56, $89, $00, $48, $89, $00, $50
	.byte $89, $00, $48, $89, $00, $56, $89, $00, $50, $89, $00, $56, $89, $00, $50
@song4ref2735:
	.byte $89, $00, $8d, $4c, $89, $00, $44, $89, $00, $4c, $89, $00, $3e, $89, $00, $42, $89, $00, $3e, $89, $00, $4e, $89, $00
	.byte $56, $89, $00, $4e
@song4ref2763:
	.byte $89, $00, $5a, $89, $00, $5c, $89, $00, $5a, $89, $00, $64, $89, $00, $5c, $89, $00, $64, $89, $00, $66, $89, $00, $64
	.byte $89, $00, $66
	.byte $ff, $0e
	.word @song4ref2763
	.byte $6e, $8b, $64, $8b, $6e, $8b, $72, $8b, $6e, $99, $6a, $8b, $6e, $8b, $6a
	.byte $ff, $37
	.word @song4ref2735
	.byte $89, $00, $5a, $89, $00, $5c, $89, $00, $5a, $89, $00, $5a, $89, $00, $56, $89, $00, $5a, $89, $00, $4e, $89, $00, $54
	.byte $89, $00, $4e, $89, $00, $5a, $89, $00, $54, $89, $00, $5a, $89, $00, $54
	.byte $ff, $66
	.word @song4ref1768
	.byte $8b, $00, $8b, $40, $8b, $3e, $8b, $00, $8b
	.byte $ff, $0d
	.word @song4ref1883
	.byte $ff, $1a
	.word @song4ref1772
	.byte $ff, $27
	.word @song4ref1899
	.byte $ff, $3d
	.word @song4ref1835
	.byte $ff, $3c
	.word @song4ref1836
	.byte $ff, $24
	.word @song4ref1836
	.byte $00, $8b
	.byte $ff, $13
	.word @song4ref1322
	.byte $99, $00, $8b, $f9, $e5, $fd
	.word @song4ch1loop
@song4ch2:
@song4ch2loop:
	.byte $d3, $f9, $91, $b2, $6a, $d1, $f9, $83, $70, $8b, $6a, $8b, $66, $8b, $6a, $b5, $b4, $40, $8b, $00, $a7, $40, $8b, $b2
	.byte $70, $8b, $6a, $8b, $66, $8b, $b4, $40, $8b, $b2, $70, $8b, $6a, $8b, $66, $8b, $b4, $40, $8b, $b2, $70, $8b, $6a, $8b
	.byte $66, $8b
@song4ref2944:
	.byte $b4, $40, $8b
@song4ref2947:
	.byte $b2, $2c, $8b, $44, $85, $00, $83, $2c, $8b, $b4, $40, $8b, $b2, $2c, $85, $00, $83, $2c, $93, $00, $83, $b4, $40, $8b
	.byte $b2, $24, $85, $00, $83, $3a, $8b, $3c, $8b, $b4, $40, $8b, $b2, $3c, $8b, $3a, $85, $00, $83, $32, $85
@song4ref2992:
	.byte $00, $83, $b4, $46, $8b, $b2, $32, $8b, $4a, $85, $00, $83, $32, $8b, $b4, $46, $8b, $b2, $32, $85, $00, $83, $32
@song4ref3015:
	.byte $93, $00, $83
@song4ref3018:
	.byte $b4, $3c, $8b, $b2, $28, $8b, $40, $85, $00, $83, $28, $8b, $b4, $3c, $8b, $b2, $28, $85, $00, $83, $28, $93, $00, $83
	.byte $ff, $14
	.word @song4ref2944
	.byte $b4, $38, $8b, $b2, $24, $8b, $3c, $85, $00, $83, $24, $8b, $b4, $38, $8b, $b2, $24, $85, $00, $83, $24, $93
	.byte $ff, $16
	.word @song4ref2992
@song4ref3070:
	.byte $b4, $36, $8b, $b2, $22, $8b, $3a, $85, $00, $83, $22, $8b, $b4, $36, $8b, $b2, $22, $85, $00, $83, $22, $93, $00, $83
	.byte $ff, $2a
	.word @song4ref2944
@song4ref3097:
	.byte $b4, $40, $8b, $b2, $32, $8b, $4a, $85, $00, $83, $32, $8b, $b4, $40, $8b, $b2, $32, $85, $00, $83, $32
@song4ref3118:
	.byte $93, $00, $83, $b4, $40, $8b, $b2, $28, $8b, $40, $85, $00, $83, $28, $8b, $b4, $40, $8b, $b2, $28, $85, $00, $83, $28
	.byte $93, $00, $83
	.byte $ff, $17
	.word @song4ref2944
@song4ref3148:
	.byte $8b, $3c, $85, $00, $83, $24, $8b, $b4, $40, $8b, $b2, $24, $85, $00, $83, $24, $93, $00, $83
	.byte $ff, $16
	.word @song4ref3097
@song4ref3170:
	.byte $00, $8b
@song4ref3172:
	.byte $b2, $3a, $85, $00, $83, $22, $8b, $b4, $40, $93, $00, $83, $b2, $22, $93, $00, $83
	.byte $ff, $2a
	.word @song4ref2944
	.byte $ff, $28
	.word @song4ref3097
	.byte $ff, $17
	.word @song4ref2944
	.byte $ff, $11
	.word @song4ref3148
	.byte $ff, $15
	.word @song4ref3097
	.byte $99, $b2, $3c, $85, $00, $83, $24, $8b, $b4, $40, $93, $00, $83, $b2, $24, $93, $00, $83
	.byte $ff, $2a
	.word @song4ref2944
	.byte $ff, $28
	.word @song4ref3097
	.byte $ff, $17
	.word @song4ref2944
	.byte $ff, $11
	.word @song4ref3148
	.byte $ff, $15
	.word @song4ref3097
@song4ref3237:
	.byte $99, $b2, $40, $85, $00, $83, $28, $8b, $b4, $40, $93, $00, $83, $b2, $28, $93, $00, $83
	.byte $ff, $2a
	.word @song4ref2944
	.byte $ff, $28
	.word @song4ref3097
	.byte $ff, $17
	.word @song4ref2944
	.byte $ff, $11
	.word @song4ref3148
	.byte $ff, $16
	.word @song4ref3097
	.byte $ff, $14
	.word @song4ref2947
	.byte $ff, $28
	.word @song4ref2947
	.byte $ff, $28
	.word @song4ref3097
	.byte $ff, $17
	.word @song4ref2944
	.byte $ff, $11
	.word @song4ref3148
	.byte $ff, $16
	.word @song4ref3097
	.byte $ff, $10
	.word @song4ref3170
	.byte $ff, $14
	.word @song4ref3018
	.byte $b4, $3c, $8b, $b2, $20, $85, $00, $83, $36, $8b, $38, $8b, $b4, $3c, $8b, $b2, $38, $8b, $36, $85, $00, $83, $2e, $85
@song4ref3318:
	.byte $00, $83, $b4, $3c, $8b, $b2, $2e, $8b, $46, $85, $00, $83, $2e, $8b, $b4, $3c, $8b, $b2, $2e, $85, $00, $83, $2e, $93
	.byte $00, $83, $b4, $3c, $8b, $b2, $24, $8b, $3c, $85, $00, $83, $24, $8b, $b4, $3c, $8b, $b2, $24, $85, $00, $83, $24
	.byte $ff, $17
	.word @song4ref3015
@song4ref3368:
	.byte $b4, $3c, $8b, $b2, $20, $8b, $38, $85, $00, $83, $20, $8b, $b4, $3c, $8b, $b2, $20, $85, $00, $83, $20, $93
	.byte $ff, $17
	.word @song4ref3318
	.byte $99, $b2, $38, $85, $00, $83, $20, $8b, $b4, $3c, $93, $00, $83, $b2, $20
	.byte $ff, $17
	.word @song4ref3015
	.byte $b4, $40, $8b, $b2, $24
	.byte $ff, $11
	.word @song4ref3148
	.byte $b4, $28, $8b, $b2, $1a, $8b, $32, $85, $00, $83, $1a, $8b, $b4, $28, $8b, $b2, $1a, $85, $00, $83, $1a
@song4ref3440:
	.byte $93, $00, $83, $b4, $36, $8b, $b2, $1e, $8b, $36, $85, $00, $83, $1e, $8b, $b4, $36, $8b, $b2, $1e, $85, $00, $83, $1e
	.byte $ff, $17
	.word @song4ref3015
	.byte $ff, $12
	.word @song4ref3368
	.byte $ff, $17
	.word @song4ref3318
	.byte $99, $b2, $36, $85, $00, $83, $1e, $8b, $b4, $3c, $93, $00, $83, $b2, $1e
	.byte $ff, $17
	.word @song4ref3118
	.byte $b4, $40, $8b, $b2, $24
	.byte $ff, $11
	.word @song4ref3148
@song4ref3499:
	.byte $b4, $40, $8b, $b2, $20, $8b, $38, $85, $00, $83, $20, $8b, $b4, $40, $8b, $b2, $20, $85, $00, $83, $20
@song4ref3520:
	.byte $93, $00, $83, $b4, $40, $8b, $b2, $1e, $8b, $36, $85, $00, $83, $1e, $8b, $b4, $40, $8b, $b2, $1e, $85, $00, $83, $1e
	.byte $ff, $17
	.word @song4ref3118
	.byte $ff, $12
	.word @song4ref3368
@song4ref3550:
	.byte $00, $83, $b4, $44, $8b, $b2, $24, $8b, $3c, $85, $00, $83, $24, $8b, $b4, $44, $8b, $b2, $24, $85, $00, $83, $24
	.byte $ff, $14
	.word @song4ref3520
	.byte $ff, $17
	.word @song4ref3118
	.byte $b4, $40, $8b, $b2, $24
	.byte $ff, $11
	.word @song4ref3148
	.byte $ff, $25
	.word @song4ref3499
	.byte $93, $00, $83
	.byte $ff, $12
	.word @song4ref3368
	.byte $ff, $13
	.word @song4ref3550
	.byte $93, $00, $83, $b4, $40, $8b, $b2, $1e, $8b, $36, $99, $b4, $42, $8b, $b2, $20, $8b, $38, $99, $b4, $46, $8b, $b2, $24
	.byte $8b, $3c, $99, $b4, $48, $8b, $b2, $26, $8b, $3e, $99, $b4, $4a, $8b, $b2, $28, $8b, $40, $99, $b4, $4c, $8b, $b2, $2a
	.byte $8b, $42, $99, $b4, $4e, $8b, $b2, $2c, $8b, $44, $99, $b4, $52, $8b, $b2, $30, $8b, $48, $99
	.byte $ff, $14
	.word @song4ref3070
	.byte $b4, $36, $8b, $b2, $1a, $85, $00, $83, $30, $8b, $32, $8b, $b4, $36, $8b, $b2, $32, $8b, $30, $85, $00, $83, $28, $85
@song4ref3693:
	.byte $00, $83, $b4, $36, $8b, $b2, $28, $8b, $40, $85, $00, $83, $28, $8b, $b4, $36, $8b, $b2, $28, $85, $00, $83, $28
	.byte $ff, $14
	.word @song4ref3440
	.byte $93, $00, $83
	.byte $ff, $14
	.word @song4ref3070
	.byte $b4, $36, $8b, $b2, $1a, $8b, $32, $85, $00, $83, $1a, $8b, $b4, $36, $8b, $b2, $1a, $85, $00, $83, $1a, $93
	.byte $ff, $13
	.word @song4ref3693
	.byte $93, $00, $83, $b4, $36, $99, $b2, $30, $85, $00, $83, $18, $8b, $b4, $36, $93, $00, $83, $b2, $18
@song4ref3770:
	.byte $93, $00, $83, $b4, $3a, $8b, $b2, $26, $8b, $3e, $85, $00, $83, $26, $8b, $b4, $3a, $8b, $b2, $26, $85, $00, $83, $26
	.byte $93, $00, $83, $b4, $3a, $8b, $b2, $1e, $85, $00, $83, $34, $8b, $36, $8b, $b4, $3a, $8b, $b2, $36, $8b, $34, $85, $00
	.byte $83, $2c, $85
@song4ref3821:
	.byte $00, $83, $b4, $3a, $8b, $b2, $2c, $8b, $44, $85, $00, $83, $2c, $8b, $b4, $3a, $8b, $b2, $2c, $85, $00, $83, $2c, $93
	.byte $00, $83, $b4, $3a, $8b, $b2, $22, $8b, $3a, $85, $00, $83, $22, $8b, $b4, $3a, $8b, $b2, $22, $85, $00, $83, $22
	.byte $ff, $1a
	.word @song4ref3770
	.byte $8b, $36, $85, $00, $83, $1e, $8b, $b4, $3a, $8b, $b2, $1e, $85, $00, $83, $1e, $93
	.byte $ff, $17
	.word @song4ref3821
	.byte $99, $b2, $34, $85, $00, $83, $1c, $8b, $b4, $3a, $93, $00, $83, $b2, $1c, $93, $00, $83
	.byte $ff, $2a
	.word @song4ref2944
	.byte $ff, $28
	.word @song4ref3097
	.byte $ff, $17
	.word @song4ref2944
	.byte $ff, $11
	.word @song4ref3148
	.byte $ff, $15
	.word @song4ref3097
	.byte $ff, $0f
	.word @song4ref3237
	.byte $ff, $2a
	.word @song4ref2944
	.byte $ff, $28
	.word @song4ref3097
	.byte $ff, $17
	.word @song4ref2944
	.byte $ff, $11
	.word @song4ref3148
	.byte $ff, $15
	.word @song4ref3097
	.byte $ff, $0f
	.word @song4ref3237
	.byte $ff, $17
	.word @song4ref2944
	.byte $ff, $11
	.word @song4ref3148
	.byte $ff, $15
	.word @song4ref3097
	.byte $ff, $0f
	.word @song4ref3237
	.byte $ff, $17
	.word @song4ref2944
	.byte $ff, $11
	.word @song4ref3148
	.byte $b4, $40, $99
	.byte $ff, $0e
	.word @song4ref3172
	.byte $2c, $eb, $00, $f9, $e5, $fd
	.word @song4ch2loop
@song4ch3:
@song4ch3loop:
	.byte $d3, $f9, $e5, $f9, $e5, $f9, $e5, $a6, $5c, $cb, $00, $f9, $95, $f9, $e5, $f9, $e5, $ef, $aa, $4e, $8b, $4e, $8b, $a4
	.byte $40, $8b, $aa, $4e, $8b, $4e, $99, $4e, $8b, $4e, $8b
@song4ref4013:
	.byte $a6
@song4ref4014:
	.byte $5c
@song4ref4015:
	.byte $99, $a8, $5c, $8b, $a4, $40, $8b, $aa, $4e, $99, $a4, $40, $8b, $a8, $5c, $8b, $a4, $40, $99, $a8, $5c, $99, $aa, $4e
	.byte $99, $a8, $5c, $8b, $5c, $8b, $a4, $40
	.byte $ff, $12
	.word @song4ref4015
@song4ref4050:
	.byte $99, $a4, $40
@song4ref4053:
	.byte $99, $a8, $5c, $8b, $a4, $40
@song4ref4059:
	.byte $8b, $aa, $4e, $99, $a4, $40, $99, $40, $99, $a8, $5c, $99, $aa, $4e, $99, $a8, $5c, $8b
@song4ref4077:
	.byte $aa, $4e, $8b, $a4, $40, $99, $a8, $5c, $8b, $a4, $40, $8b, $aa, $4e, $99, $a4, $40, $8b, $a8, $5c, $8b, $a4, $40, $8b
	.byte $40, $99, $a8, $5c, $8b, $aa, $4e, $99, $a8, $5c, $99
	.byte $ff, $17
	.word @song4ref4013
	.byte $ff, $12
	.word @song4ref4015
	.byte $ff, $2b
	.word @song4ref4050
	.byte $ff, $17
	.word @song4ref4013
	.byte $ff, $12
	.word @song4ref4015
	.byte $99, $a6, $5c
	.byte $ff, $29
	.word @song4ref4053
	.byte $ff, $17
	.word @song4ref4013
	.byte $ff, $12
	.word @song4ref4015
	.byte $99, $a6, $5c
	.byte $ff, $22
	.word @song4ref4053
	.byte $8b, $a8, $5c, $8b, $aa, $4e, $8b, $4e, $8b, $4e, $8b, $a6, $5c, $99
	.byte $ff, $17
	.word @song4ref4014
	.byte $ff, $12
	.word @song4ref4015
	.byte $ff, $2b
	.word @song4ref4050
	.byte $ff, $17
	.word @song4ref4013
	.byte $ff, $12
	.word @song4ref4015
	.byte $ff, $2b
	.word @song4ref4050
	.byte $ff, $14
	.word @song4ref4013
	.byte $ff, $0f
	.word @song4ref4077
	.byte $99, $a8, $5c, $99, $aa, $4e, $99, $a8, $5c
	.byte $ff, $21
	.word @song4ref4050
	.byte $aa, $4e, $8b, $4e, $99, $a4, $40, $8b, $aa, $4e, $99, $a4, $40, $8b, $aa, $4e
@song4ref4211:
	.byte $8b, $a6, $5c, $b5, $a4, $40, $99, $40, $8b, $a8, $5c
@song4ref4222:
	.byte $8b, $aa, $4e, $a7, $a8, $5c, $8b, $a4, $40, $b5, $40, $a7, $a8, $5c, $8b, $a4, $40, $99, $40, $99, $aa, $4e, $8b, $a4
	.byte $40, $a7, $40, $99, $a8, $5c, $8b, $5c
	.byte $ff, $20
	.word @song4ref4211
	.byte $ff, $20
	.word @song4ref4211
	.byte $ff, $0f
	.word @song4ref4222
	.byte $a6, $5c, $99, $a4, $40, $8b, $a8, $5c, $8b, $aa, $4e, $99, $a4, $40, $8b, $a8, $5c, $8b, $aa, $4e, $99, $a4, $40, $8b
	.byte $a8, $5c, $8b, $aa, $4e, $99, $a4, $40, $8b, $a8, $5c, $8b, $aa, $4e, $8b, $4e, $8b, $4e, $99, $4e, $8b, $4e, $8b, $4e
	.byte $99, $4e, $8b, $4e, $8b, $4e, $8b, $4e, $8b, $a6, $5c, $b5
	.byte $ff, $17
	.word @song4ref4014
	.byte $ff, $12
	.word @song4ref4015
	.byte $ff, $2b
	.word @song4ref4050
	.byte $ff, $17
	.word @song4ref4013
	.byte $ff, $12
	.word @song4ref4015
	.byte $99, $a4, $40, $99, $a8, $5c, $8b, $5c
	.byte $ff, $25
	.word @song4ref4059
	.byte $ff, $17
	.word @song4ref4013
	.byte $ff, $12
	.word @song4ref4015
	.byte $99, $a6, $5c
	.byte $ff, $29
	.word @song4ref4053
	.byte $ff, $17
	.word @song4ref4013
	.byte $ff, $12
	.word @song4ref4015
	.byte $99, $a6, $5c
	.byte $ff, $29
	.word @song4ref4053
	.byte $a6, $5c
	.byte $ff, $29
	.word @song4ref4053
	.byte $a6, $5c
	.byte $ff, $13
	.word @song4ref4053
	.byte $4e, $99, $4e, $99, $4e, $8b, $4e, $8b, $4e, $8b, $4e, $8b, $a6, $5c, $cb, $00, $9f, $f9, $e5, $fd
	.word @song4ch3loop
@song4ch4:
@song4ch4loop:
	.byte $d3
@song4ref4407:
	.byte $f9, $e5, $f9, $e5, $f9, $e5, $f9, $e5, $f9, $e5, $f9, $e5, $f9, $e5
	.byte $ff, $0e
	.word @song4ref4407
	.byte $ff, $0e
	.word @song4ref4407
	.byte $ff, $0e
	.word @song4ref4407
	.byte $ff, $0e
	.word @song4ref4407
	.byte $ff, $0e
	.word @song4ref4407
	.byte $ff, $0e
	.word @song4ref4407
	.byte $ff, $0e
	.word @song4ref4407
	.byte $ff, $0e
	.word @song4ref4407
	.byte $f9, $e5, $f9, $e5, $fd
	.word @song4ch4loop
